<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Contactmoment 4: Respons computer lab – Statistiek B</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/cookie-consent/cookie-consent.js"></script>
<link href="../../site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-b86774849c83f8842429632de05d13be.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Geen resultaten",
    "search-matching-documents-text": "Gevonden documenten",
    "search-copy-link-title": "Kopieer link om te zoeken",
    "search-hide-matches-text": "Extra overeenkomsten verbergen",
    "search-more-match-text": "meer overeenkomst in dit document",
    "search-more-matches-text": "meer overeenkomsten in dit document",
    "search-clear-button-title": "Wissen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuleren",
    "search-submit-button-title": "Verzenden",
    "search-label": "Zoeken"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-WB6XE1H6V1"></script>

<script type="text/plain" cookie-consent="tracking">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-WB6XE1H6V1', { 'anonymize_ip': true});
</script>

<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"simple",
  "consent_type":"implied",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary","functionality","tracking","targeting"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  ,
"language":"nl"
  });
});
</script> 
  

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <div id="quarto-announcement" data-announcement-id="b0e362a38869e05bc3e01903c80d0932" class="alert alert-primary hidden"><i class="bi bi-info-circle quarto-announcement-icon"></i><div class="quarto-announcement-content">
<p><strong>Alert</strong> - deze website is nog in ontwikkeling - feedback altijd welkom via sven.demaeyer@uantwperen.be</p>
</div><i class="bi bi-x-lg quarto-announcement-action"></i></div>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Contactmoment 4: Respons computer lab</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Zoeken" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
      <a href="../../index.html" class="sidebar-logo-link">
      <img src="../../images/STAT B.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main tools-wide">
    <a href="https://www.uantwerpen.be/nl/" title="uantwerpen.be/nl/" class="quarto-navigation-tool px-1" aria-label="uantwerpen.be/nl/"><i class="bi bi-globe"></i></a>
    <a href="https://github.com/Sdemaeyer2/STATB_2425" title="Statistiek B" class="quarto-navigation-tool px-1" aria-label="Statistiek B"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Schakel leesmodus">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Zoeken"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welkom</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../OLP.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Open Leer Pakket</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../Contactmomenten/Contactmomenten.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Contactmomenten</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Contactmomenten/C1/C1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">C1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Contactmomenten/C2/C2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">C2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Contactmomenten/C3/C3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">C3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Contactmomenten/C4/C4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">C4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Contactmomenten/C5/C5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">C5</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Contactmomenten/C6/C6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">C6</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Contactmomenten/C7/C7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">C7</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../Penguins.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Online (R) oefeningen</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Zelftest_t_test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">t-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Zelftest_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Zelftest_kruistabellen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Kruistabellen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Zelftest_correlaties.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Correlaties</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../computer_labs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Computer labs</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">ZSO</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ZSO/ZSO1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO1: van vraag naar methode</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ZSO/ZSO2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO2: t-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ZSO/ZSO3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO3: ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ZSO/ZSO4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO4: Kruistabellen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ZSO/ZSO5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO5: Correlaties</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ZSO/ZSO6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO6: Bivariate regressie</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ZSO/ZSO7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO7: Multivariate regressie en assumpties</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ZSO/ZSO8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO8: Dummy-variabelen en interacties</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../Rapporteren.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Rapporteren</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../t_test_Rapportage.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">t-test rapporteren</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ANOVA_Rapportage.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ANOVA rapporteren</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Screencasts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Screencasts</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Extra materiaal</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Extra/Projecten.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Projecten in RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Extra/Quarto_documenten.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quarto documenten</span></a>
  </div>
</li>
          <li class="sidebar-item">
 <span class="menu-text">Data-manipulatie met dplyr</span>
  </li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../studiewijzer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Studiewijzer</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Op deze pagina</h2>
   
  <ul class="collapse">
  <li><a href="#voorbereiding" id="toc-voorbereiding" class="nav-link active" data-scroll-target="#voorbereiding">Voorbereiding</a></li>
  <li><a href="#oefening-1" id="toc-oefening-1" class="nav-link" data-scroll-target="#oefening-1">Oefening 1</a></li>
  <li><a href="#oefening-2" id="toc-oefening-2" class="nav-link" data-scroll-target="#oefening-2">Oefening 2</a></li>
  <li><a href="#oefening-3" id="toc-oefening-3" class="nav-link" data-scroll-target="#oefening-3">Oefening 3</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Andere formaten</h2><ul><li><a href="Respons_C4.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Contactmoment 4: Respons computer lab</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Belangrijk
</div>
</div>
<div class="callout-body-container callout-body">
<p>Vooraleer je de oefeningen kan oplossen is het belangrijk om zowel de dataset te laden, het pakket <code>car</code> te activeren en ook de OLP2 Functies te activeren.</p>
</div>
</div>
<section id="voorbereiding" class="level2">
<h2 class="anchored" data-anchor-id="voorbereiding">Voorbereiding</h2>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="bi bi-journal"></i> Voorbereiding
</div>
</div>
<div class="callout-body-container callout-body">
<p>Deze hele opdracht bevat drie oefeningen die op elkaar doorbouwen. Vooraleer we starten met de 3 oefeningen in <code>R</code> op te lossen, vragen we je enkele acties te ondernemen ter voorbereiding:</p>
<ul>
<li><p>Teken de modellen uit de 3 oefeningen</p></li>
<li><p>Maak van alle variabelen die worden gebruikt in de oefeningen een z-score variant: <code>Interest.na</code>, <code>Interest.voor</code>, <code>Projectinteressant</code>, <code>Projectleuk</code>, <code>Projectbijgeleerd</code> en <code>Projectmoeilijk</code></p></li>
<li><p>Om de verschillende modellen te kunnen vergelijken, maken we meteen gebruik van een databestand zonder ontbrekende observaties (zonder NA’s) voor alle variabelen die je nodig hebt. (functie: <code>na.omit()</code>)</p></li>
</ul>
</div>
</div>
<p>We starten met het uittekenen van de 3 modellen uit de onderzoeksvragen in de opdracht.</p>
<p><img src="Modellen_gevisualiseerd.jpg" class="img-fluid" width="500"></p>
<p>Een tweede voorbereidende stap is het herschalen van alle betrokken variabelen naar z-scores. Merk op dat we de herschaalde variabelen wegschrijven in telkens een nieuwe variabele eerder dan de originele variabele te overschrijven. In de verdere oefeningen maken we gebruik van deze nieuwe variabelen. Hieronder maken we gebruik van de functie <code>scale()</code>, maar je kan net zo goed de functie <code>z-score()</code> gebruiken.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>Techniek<span class="sc">$</span>Interest.voorZ <span class="ot">&lt;-</span> <span class="fu">scale</span>(Techniek<span class="sc">$</span>Interest.voor)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>Techniek<span class="sc">$</span>Interest.naZ <span class="ot">&lt;-</span> <span class="fu">scale</span>(Techniek<span class="sc">$</span>Interest.na)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>Techniek<span class="sc">$</span>ProjectinteressantZ <span class="ot">&lt;-</span> <span class="fu">scale</span>(Techniek<span class="sc">$</span>Projectinteressant)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>Techniek<span class="sc">$</span>ProjectmoeilijkZ <span class="ot">&lt;-</span> <span class="fu">scale</span>(Techniek<span class="sc">$</span>Projectmoeilijk)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>Techniek<span class="sc">$</span>ProjectleukZ <span class="ot">&lt;-</span> <span class="fu">scale</span>(Techniek<span class="sc">$</span>Projectleuk)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>Techniek<span class="sc">$</span>ProjectbijgeleerdZ <span class="ot">&lt;-</span> <span class="fu">scale</span>(Techniek<span class="sc">$</span>Projectbijgeleerd)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>De laatste stap is het aanmaken van een dataframe waarin enkel de data bewaard zijn van respondenten die voor geen van deze betrokken variabelen een ontbrekende waarde hebben. Dit doen we aan de hand van de <code>na.omit()</code> functie.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>DataC4 <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  Techniek[ ,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">c</span>(<span class="st">"Interest.voorZ"</span>, </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>              <span class="st">"Interest.naZ"</span>,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>              <span class="st">"ProjectinteressantZ"</span>, </span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>              <span class="st">"ProjectmoeilijkZ"</span>,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>              <span class="st">"ProjectleukZ"</span>, </span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>              <span class="st">"ProjectbijgeleerdZ"</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>              )</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>            ]</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Opmerking
</div>
</div>
<div class="callout-body-container callout-body">
<p>In het bovenstaande code-blok heb ik bewust een code-stijl gebruikt die veel overzichtelijker is. Door de code overheen verschillende lijnen te spreiden kan je makkelijker de haakjes van elkaar onderscheiden en zie je welke argumenten in welk onderdeel behoren.</p>
</div>
</div>
</section>
<section id="oefening-1" class="level2">
<h2 class="anchored" data-anchor-id="oefening-1">Oefening 1</h2>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="bi bi-journal-richtext"></i> Oefening 1
</div>
</div>
<div class="callout-body-container callout-body">
<p>In een eerste model (Model1) onderzoeken we in welke mate het interessant vinden van het project (<code>Projectinteressant</code>) een invloed heeft op de interesse in techniek na het project (<code>Interest.na</code>).</p>
<ol type="a">
<li><p>Schat het model en bespreek de relevante parameters</p></li>
<li><p>Ga de assumpties m.b.t. dit model na</p></li>
</ol>
</div>
</div>
<ol type="a">
<li></li>
</ol>
<p>We starten met het schatten van het model. Daarbij maak ik uiteraard gebruik van de nieuw aangemaakte dataframe hierboven: <code>DataC4</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>Model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Interest.naZ<span class="sc">~</span>ProjectinteressantZ, <span class="at">data =</span> DataC4)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Model1)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Interest.naZ ~ ProjectinteressantZ, data = DataC4)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.4811 -0.6902 -0.0363  0.6031  2.6525 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         -0.004071   0.019856  -0.205    0.838    
ProjectinteressantZ  0.324501   0.019861  16.339   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9502 on 2288 degrees of freedom
Multiple R-squared:  0.1045,    Adjusted R-squared:  0.1041 
F-statistic:   267 on 1 and 2288 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><p>R-kwadraat = 0.10: het gaat om een medium effect (10% verklaarde variantie in <code>Interest.naZ</code>);</p></li>
<li><p>met p &lt; 0.05 voorhet gehele model: kans dat we deze verklaarde variantie zouden vaststellen in onze steekproef indien H0 opgaat in de populatie is kleiner dan 5%. Dus we verwachten dat dit model in de populatie WEL variantie verklaart in <code>Interest.naZ</code>.</p></li>
<li><p>parameterschatting van het intercept = -0.004: voor een leerling die 0 scoort op <code>ProjectinteressantZ</code> verwachten we een score van -0.004 op <code>Interest.naZ</code></p></li>
<li><p>met p &gt; 0.05 voor de parameterschatting van het intercept: kans dat we deze interceptwaarde vaststellen in onze steekproef indien H0 opgaat in de populatie is groter dan 5%. Dus we verwachten dit NIET in de populatie terug te vinden. Het verwachte intercept in de populatie is dus 0. Dit is niet verwonderlijk aangezien zowel de onafhankelijke (<code>ProjectinteressantZ</code>) als de afhankelijke variabele (<code>Interest.naZ</code>) gestandaardiseerd zijn. Het intercept geeft hier dus de score weer op <code>Interest.naZ</code> voor een leerling die gemiddeld scoort op <code>ProjectinteressantZ</code>. M.a.w., in de populatie scoren leerlingen die gemiddeld scoren op <code>ProjectinteressantZ</code> ook gemiddeld op <code>Interest.naZ</code>.</p></li>
<li><p><span class="math inline">\(\beta_{ProjectinteressantZ}\)</span> = 0.32, dus 1 SD (in standaarddeviaties uitgedrukt want z-score) hoger scoren op <code>ProjectinteressantZ</code> leidt tot 0.32 SD (in standaarddeviaties uitgedrukt want z-score) hoger scoren op <code>Interest.naZ</code></p></li>
<li><p>met p &lt; 0.05: kans dat we deze slope in onze steekproef vaststellen indien H0 opgaat in de populatie is kleiner dan 5%. Dus we verwachten dat <code>ProjectinteressantZ</code> in de populatie WEL invloed heeft op <code>Interest.naZ</code>.</p></li>
</ul>
<p><strong>Conclusie</strong></p>
<blockquote class="blockquote">
<p>De mate waarin leerlingen het project interessant vinden (<code>ProjectinteressantZ</code>), heeft een medium significant effect op hun interesse in techniek na het project (<code>Interest.naZ</code>; R² = 0.10; p &lt; 0.05). Het effect is hier statistisch significant en positief (ß = 0.32, p &lt; 0.05). Voor elke SD dat een leerling meer scoort op <code>ProjectinteressantZ</code> zal de interesse in techniek na het project (<code>Interest.naZ</code>) met 0.32 SD toenemen. Een leerling die gemiddle scoort op <code>ProjectinteressantZ</code> scoort -0.004 op <code>Interest.naZ</code>. Dit kunnen we echter niet doortrekken naar de populatie (p &gt; 0.05). In de populatie verwachten we dat een leerling die het project gemiddeld interessant vindt, ook een gemiddelde interesse in techniek na het project zal hebben.</p>
</blockquote>
<ol start="2" type="a">
<li></li>
</ol>
<p>Vervolgens gaan we de assumpties na voor dit model door verschillende visualisaties aan te maken.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Opmerking
</div>
</div>
<div class="callout-body-container callout-body">
<p>De twee laatste plots zijn <em>interactieve</em> plots. Dat wil zeggen dat je op je pc ook punten kan aanklikken en je krijgt vervolgens een nummer te zien. Dit is de case-nummer (rij-nummer) voor dat datapunt. In de output hier hebben we dat (omwille van technische redenen) niet kunnen doen.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotvenster in 4 delen (2 rijen en 2 kolommen)</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Model1)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Respons_C4_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>)) <span class="co">#zo zet je het plotvenster terug op standaardweergave</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">residuals_plot</span>(Model1)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Respons_C4_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>integer(0)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cooks_plot</span>(Model1)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Respons_C4_files/figure-html/unnamed-chunk-5-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>integer(0)</code></pre>
</div>
</div>
<p><strong>Homoscedasticiteit:</strong></p>
<p>Grafiek ‘Residuals versus Fitted’: spreiding blijft quasi gelijk naarmate de fitted value toeneemt. Dit duidt op homoscedasticiteit.</p>
<p>Grafiek ‘Scale-location plot’: de rode lijn in de plot loopt min of meer recht. Dit duidt op homoscedasticiteit.</p>
<p><strong>Errortermen normaal verdeeld:</strong></p>
<p>Grafiek ‘Q-Q plot’: alle punten vallen min of meer op de rechte lijn. Dit geeft aan dat de errortermen normaal verdeeld zijn.</p>
<p><strong>geen clustering en een lineair verband:</strong></p>
<p>Grafiek ‘Residuals versus Fitted’: op deze grafiek is geen clustering van waarnemingen terug te vinden. Noch kan je op basis van deze grafiek een niet-lineair verband vermoeden.</p>
<p><strong>wel outliers:</strong></p>
<p>Grafieken ‘Residuals plot’ &amp; ‘Cooks plot’: duidelijk aantal outliers zichtbaar. Deze zouden idealiter verwijderd moeten worden en dan zou je het model opnieuw kunnen schatten. Dat is hier niet de opdracht, dus doen we dat niet.</p>
</section>
<section id="oefening-2" class="level2">
<h2 class="anchored" data-anchor-id="oefening-2">Oefening 2</h2>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="bi bi-journal-richtext"></i> Oefening 2
</div>
</div>
<div class="callout-body-container callout-body">
<p>Wanneer blijkt dat de mate waarin de leerling het project als interessant ervaart er toe doet, kun je je natuurlijk afvragen hoe dat komt. Misschien is het zo dat leerlingen die techniek sowieso al interessant vonden voor het project (<code>Interest.voor</code>) nadien ook een hogere interesse behouden (die hadden ze tenslotte al voor het project). Om dit na te gaan, test je een tweede model (Model2) waarin je <code>Interest.voor</code> als controlevariabele aan het vorige model (Model1) toevoegt.</p>
<ol type="a">
<li><p>Is dit model (Model2) een beter model dan Model1?</p></li>
<li><p>Bespreek de relevante parameters van het beste model.</p></li>
</ol>
</div>
</div>
<ol type="a">
<li></li>
</ol>
<p>We schatten dit tweede model en vergelijken dit model met het eerste model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>Model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Interest.naZ <span class="sc">~</span> ProjectinteressantZ <span class="sc">+</span> Interest.voorZ, <span class="at">data =</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>DataC4)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(Model1, Model2)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Interest.naZ ~ ProjectinteressantZ
Model 2: Interest.naZ ~ ProjectinteressantZ + Interest.voorZ
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1   2288 2065.7                                  
2   2287 1310.5  1    755.26 1318.1 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>De Residuals Sum of Squares (RSS) van Model1 = 2065.7, RSS van Model2 = 1310.5. Gebaseerd op de F-test voor het vergelijken van beide modellen leren we dat Model 2 statistisch significant beter bij de data past dan model 1 (p &lt; 0.05). We weerhouden dus best Model 2.</p>
<ol start="2" type="a">
<li></li>
</ol>
<p>Nu we beslissen om Model2 te weerhouden, kunnen we de informatie over de parameterschattingen uit dat model opvragen in <code>R</code> via het <code>summary( )</code> commando.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Model2)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Interest.naZ ~ ProjectinteressantZ + Interest.voorZ, 
    data = DataC4)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.0384 -0.4520  0.0093  0.4924  2.7215 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         -0.003766   0.015818  -0.238    0.812    
ProjectinteressantZ  0.180850   0.016310  11.089   &lt;2e-16 ***
Interest.voorZ       0.592104   0.016309  36.305   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.757 on 2287 degrees of freedom
Multiple R-squared:  0.4319,    Adjusted R-squared:  0.4314 
F-statistic: 869.3 on 2 and 2287 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><p>R-kwadraat = 0.43: het gaat om een groot effect (43% verklaarde variantie in <code>Interest.naZ</code>);</p></li>
<li><p>Met p &lt; 0.05: kans dat we deze verklaarde variantie in onze steekproef zouden vaststellen indien H0 opgaat in de populatie is kleiner dan 5%, dus we verwachten dat dit model in de populatie WEL variantie verklaart in <code>Interest.naZ</code></p></li>
<li><p>intercept = -0.004: een leerling die 0 scoort op <code>ProjectinteressantZ</code> en <code>Interest.voor</code> scoort -0.004 op <code>Interest.naZ</code>;</p></li>
<li><p>Met p &gt; 0.05: kans dat we deze interceptwaarde in onze steekproef vaststellen indien H0 opgaat in de populatie is groter dan 5%. Dus we verwachten dit NIET in de populatie terug te vinden. Het verwachtte intercept in de populatie is dus 0. Dit is niet verwonderlijke aangezien zowel de onafhankelijke variabelen (<code>Interest.voorZ</code> en <code>ProjectinteressantZ</code>) als de afhankelijke variabele (<code>Interest.naZ</code>) zijn gestandaardiseerd. Het intercept geeft hier dus de score weer op <code>Interest.naZ</code> voor leerlingen die gemiddeld scoren op <code>Interest.voorZ</code> en <code>ProjectinteressantZ</code>. M.a.w., in de populatie scoren leerlingen die gemiddeld scoren op <code>Interest.voorZ</code> en <code>ProjectinteressantZ</code> ook gemiddeld op <code>Interessant.na</code>.</p></li>
<li><p><span class="math inline">\(\beta_{ProjectinteressantZ}\)</span> = 0.18, dus 1 SD (want z-score!) hoger scoren op <code>Projectinteressant</code> leidt tot 0.18 SD (want z-score!) hoger scoren op <code>Interest.na</code></p></li>
<li><p>Met p &lt; 0.05: kans dat we deze slope vaststellen in onze steekproef indien H0 opgaat in de populatie is kleiner dan 5%. Dus we verwachten dat <code>Projectinteressant</code> in de populatie WEL invloed heeft op <code>Interest.na</code>.</p></li>
<li><p><span class="math inline">\(\beta_{Interest.voorZ} = 0.59\)</span>, dus 1 SD (want z-score!) hoger scoren op <code>Interest.voorZ</code> leidt tot 0.59 SD (want z-score!) hoger scoren op <code>Interest.na</code></p></li>
<li><p>Met p &lt; 0.05: kans dat we deze slope vaststellen in de steekproef indien H0 opgaat in de populatie is kleiner dan 5%. Dus we verwachten dat <code>Interest.voorZ</code> in de populatie WEL invloed heeft op <code>Interest.naZ</code>.</p></li>
<li><p>Bovendien is dit effect sterker dan dat van <code>ProjectinteressantZ</code>. (Je mag de sterkte van beide effecten met elkaar vergelijken, omdat beide variabelen gestandaardiseerd zijn en dus op dezelfde schaal staan.)</p></li>
</ul>
<p><strong>Conclusie</strong></p>
<blockquote class="blockquote">
<p>Interesse in techniek voor het project (<code>Interest.voorZ</code>) en de mate waarin leerlingen het project interessant (<code>ProjectinteressantZ</code>) vinden verklaren de interesse in techniek van leerlingen na het project (<code>Interest.naZ</code>) beter als het model waarin enkel <code>ProjectinteressantZ</code> als onafhankelijke variabele is opgenomen (∆RSS = 755.26, p &lt; 0.05). Het gaat bovendien om een sterk, significant effect (R-kwadraat = 0.43, p &lt; 0.05). Het intercept is niet statistisch significant (p &gt; 0.05). Een leerling die gemiddeld scoort op <code>ProjectinteressantZ</code> en <code>Interest.voorZ</code> scoort dus ook gemiddeld op <code>Interest.naZ</code> in de populatie. Zowel <code>ProjectinteressantZ</code> als <code>Interest.voorZ</code> hebben een positief en statistisch significant (p &lt; 0.05) effect op <code>Interest.naZ</code>. Een toename van 1 SD in <code>ProjectinteressantZ</code> leidt tot een toename van 0.18 SD in <code>Interest.naZ</code>. Het effect van <code>Interest.voorZ</code> is sterker (ß = 0.59). 1 SD hoger scoren op interesse in techniek voor het project leidt tot een toename van 0.59 SD in interesse in techniek na het project.</p>
</blockquote>
</section>
<section id="oefening-3" class="level2">
<h2 class="anchored" data-anchor-id="oefening-3">Oefening 3</h2>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="bi bi-journal-richtext"></i> Oefening 3
</div>
</div>
<div class="callout-body-container callout-body">
<p>Mogelijk zorgt het opnemen van de overige variabelen die de houdingen van de leerlingen m.b.t. het techniekproject meten (‘Projectleuk’, ‘Projectbijgeleerd’, ‘Projectmoeilijk’) voor een verbetering van het model. Om dit na te gaan, test je een derde model (Model3) waarin je deze drie variabelen als controlevariabelen aan het vorige model (Model2) toevoegt.</p>
<ol type="a">
<li><p>Ga na of er geen probleem is van multicollineariteit. Pas het model indien nodig aan.</p></li>
<li><p>Is (een eventueel aangepaste versie van) Model3 een beter model dan Model2?</p></li>
<li><p>Bespreek de relevante parameters van het beste model.</p></li>
<li><p>Welke score op ‘Interest.naZ’ behaalt iemand die:</p></li>
</ol>
<ul>
<li>gemiddeld scoort op alle onafhankelijke variabelen in de steekproef</li>
<li>gemiddeld scoort op alle onafhankelijke variabelen in de populatie</li>
<li>1 SD hoger scoort voor ‘Interest.voorZ’ en 1 SD lager scoort voor ‘ProjectbijgeleerdZ’ (en op alle andere onafhankelijke variabelen 0) in de steekproef</li>
<li>1 SD hoger scoort voor ‘Interest.voorZ’ en en 1 SD lager scoort voor ‘ProjectbijgeleerdZ’ (en op alle andere onafhankelijke variabelen 0) in de populatie</li>
</ul>
<p><strong>Rond bij het berekenen van de voorspelde scores altijd af tot op 3 cijfers na de komma!</strong></p>
</div>
</div>
<ol type="a">
<li></li>
</ol>
<p>Hieronder schatten we dit model in z’n geheel en gaan meteen de multicollineariteit na aan de hand van de functie <code>vif()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>Model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Interest.naZ <span class="sc">~</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>               ProjectinteressantZ <span class="sc">+</span> </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>               Interest.voorZ <span class="sc">+</span> </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>               ProjectleukZ <span class="sc">+</span> </span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>               ProjectbijgeleerdZ <span class="sc">+</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>               ProjectmoeilijkZ, </span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> DataC4)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(Model3)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ProjectinteressantZ      Interest.voorZ        ProjectleukZ  ProjectbijgeleerdZ 
           7.041215            1.117586            5.554361            3.859391 
   ProjectmoeilijkZ 
           1.278241 </code></pre>
</div>
</div>
<p>Uit de bovenstaande output leren we dat de VIF voor <code>ProjectinteressantZ</code> 7.04 bedraagt en voor <code>ProjectleukZ</code> 5.55. Deze twee waarden duiden op een mogelijk probleem van multicollinearitet. We kunnen eveneens de correlatie berekenen tussen deze twee variabelen om meer zicht te krijgen op hun onderlinge samenhang al verklaring voor het mogelijk multicollineariteitsprobleem.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(DataC4<span class="sc">$</span>ProjectinteressantZ, DataC4<span class="sc">$</span>ProjectleukZ)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  DataC4$ProjectinteressantZ and DataC4$ProjectleukZ
t = 99.142, df = 2288, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.8926227 0.9081126
sample estimates:
      cor 
0.9006534 </code></pre>
</div>
</div>
<p>Deze variabelen blijken zeer sterk te correleren (r = 0.90). Daarom is het aangewezen om het model de herdraaien zonder één van beide variabelen. Anders levert dit vertekende significantietoetsen voor de betrokken variabelen op. Daarom herschatten we het model zonder de controlevariabele <code>ProjectleukZ</code> (zie Model4).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>Model4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Interest.naZ <span class="sc">~</span> </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>               ProjectinteressantZ <span class="sc">+</span> </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>               Interest.voorZ <span class="sc">+</span> </span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>               ProjectbijgeleerdZ <span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>               ProjectmoeilijkZ, </span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> DataC4)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(Model4)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ProjectinteressantZ      Interest.voorZ  ProjectbijgeleerdZ    ProjectmoeilijkZ 
           3.671585            1.107204            3.725005            1.278237 </code></pre>
</div>
</div>
<p>Uit de output blijkt dat het multicollineariteitsprobleem in Model4 is opgelost. We werken dus verder met Model4.</p>
<ol start="2" type="a">
<li></li>
</ol>
<p>Vervolgens gaan we dit Model4 vergelijken met Model2 om te weten of dit model beter de data vooropelt.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(Model2, Model4)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Interest.naZ ~ ProjectinteressantZ + Interest.voorZ
Model 2: Interest.naZ ~ ProjectinteressantZ + Interest.voorZ + ProjectbijgeleerdZ + 
    ProjectmoeilijkZ
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1   2287 1310.5                                  
2   2285 1297.3  2    13.166 11.595 9.765e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>RSS voor Model2 = 1310.5; RSS voor Model4 = 1297.3, p &lt; 0.05 Model4 is statistisch significant beter dan Model2. Model4 heeft een lagere RSS. Het verschil in RSS (∆RSS = 13.17) is statistisch significant (p &lt; 0.05). Dus we kunnen concluderen dat Model4 de verschillen in interesse in techniek na het project (<code>Interest.naZ</code>) beter voorspelt dan Model2 (∆RSS = 13.17, p &lt; 0.05).</p>
<ol start="3" type="a">
<li></li>
</ol>
<p>We vragen de parameterschattingen van Model4 op.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Model4)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Interest.naZ ~ ProjectinteressantZ + Interest.voorZ + 
    ProjectbijgeleerdZ + ProjectmoeilijkZ, data = DataC4)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.0431 -0.4473  0.0046  0.4895  2.7835 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         -0.003901   0.015746  -0.248    0.804    
ProjectinteressantZ  0.188626   0.030178   6.250 4.87e-10 ***
Interest.voorZ       0.576293   0.016572  34.776  &lt; 2e-16 ***
ProjectbijgeleerdZ   0.034290   0.030389   1.128    0.259    
ProjectmoeilijkZ    -0.085936   0.017852  -4.814 1.58e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7535 on 2285 degrees of freedom
Multiple R-squared:  0.4376,    Adjusted R-squared:  0.4366 
F-statistic: 444.5 on 4 and 2285 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><p>R-kwadraat = 0.44: het gaat om een groot effect (44% verklaarde variantie in <code>Interest.naZ</code>)</p></li>
<li><p>Met p &lt; 0.05: kans dat we dit vaststellen in onze steekproef indien H0 opgaat in de populatie is kleiner dan 5%. Dus we verwachten dat dit model in de populatie WEL variantie verklaart in <code>Interest.naZ</code>.</p></li>
<li><p>intercept = -0.004: een leerling die 0 scoort op <code>ProjectinteressantZ</code>, <code>Interest.voor</code>, <code>ProjectbijgeleerdZ</code> en <code>ProjectmoeilijkZ</code> behaalt -0.004 op <code>Interest.naZ</code></p></li>
<li><p>Met p &gt; 0.05: kans dat we deze waarde voor het intercept in onze steekproef vaststellen indien H0 opgaat in de populatie is groter dan 5%. Dus we verwachten dit NIET in de populatie terug te vinden. Het verwachtte intercept in de populatie is dus 0. Dit is niet verwonderlijke aangezien zowel de onafhankelijke variabelen als de afhankelijke variabele gestandaardiseerd zijn. Het intercept geeft hier dus de score weer op <code>Interest.naZ</code>voor leerlingen die gemiddeld scoren op alle onafhankelijke variabelen. M.a.w., in de populatie scoren leerlingen die gemiddeld scoren op <code>Interest.voorZ</code>, <code>ProjectinteressantZ</code>, <code>ProjectmoeilijkZ</code> en <code>ProjectbijgeleerdZ</code> ook gemiddeld op <code>Interest.naZ</code>.</p></li>
<li><p><span class="math inline">\(\beta_{ProjectinteressantZ}\)</span> = 0.19, dus 1 SD (want z-score!) hoger scoren op <code>ProjectinteressantZ</code> leidt tot 0.19 SD (want z-score!) hoger scoren op <code>Interest.naZ</code></p></li>
<li><p>Met p &lt; 0.05: kans dat we deze slope vaststellen in onze steekproef indien H0 opgaat in de populatie is kleiner dan 5%. Dus we verwachten dat <code>ProjectinteressantZ</code> in de populatie WEL invloed heeft op <code>Interest.naZ</code>.</p></li>
<li><p><span class="math inline">\(\beta_{Interest.voorZ}\)</span> = 0.58, dus 1 SD (want z-score!) hoger scoren op <code>Interest.voorZ</code>leidt tot 0.58 SD (want z-score!) hoger scoren op <code>Interest.naZ</code></p></li>
<li><p>Met p &lt; 0.05: kans dat we deze slope vaststellen in de steekproef indien H0 opgaat in de populatie is kleiner dan 5%. Dus we verwachten dat <code>Interest.voorZ</code> in de populatie WEL invloed heeft op <code>Interest.naZ</code>. Bovendien is dit effect sterker dan dat van <code>ProjectinteressantZ</code> en dat van <code>ProjectmoeilijkZ</code>. (Je mag de sterkte van deze effecten met elkaar vergelijken, omdat beide variabelen gestandaardiseerd zijn en dus op dezelfde schaal staan.)</p></li>
<li><p><span class="math inline">\(\beta_{ProjectibijgeleerdZ}\)</span> = 0.03, dus 1 SD (want z-score!) hoger scoren op <code>ProjectbijgeleerdZ</code> leidt tot 0.03 SD (want z-score!) hoger scoren op <code>Interest.naZ</code></p></li>
<li><p>Met p &gt; 0.05: kans dat H0 opgaat in de populatie is groter dan 5%. Dus we verwachten dat <code>ProjectinteressantZ</code> in de populatie GEEN invloed heeft op <code>Interest.naZ</code>.</p></li>
<li><p><span class="math inline">\(\beta_{ProjectmoeilijkZ}\)</span> = -0.09, dus 1 SD (want z-score!) hoger scoren op <code>ProjectmoeilijkZ</code> leidt tot 0.09 SD (want z-score!) lager scoren op <code>Interest.naZ</code></p></li>
<li><p>Met p &lt; 0.05: kans dat we deze hellingsgraad vastellen in onze steekproef indien H0 opgaat in de populatie is kleiner dan 5%. Dus we verwachten dat <code>ProjectmoeilijkZ</code> in de populatie WEL invloed heeft op <code>Interest.naZ</code>.</p></li>
</ul>
<p><strong>Conclusie:</strong></p>
<blockquote class="blockquote">
<p><code>ProjectinteressantZ</code>, <code>Interest.voorZ</code>, <code>ProjectbijgeleerdZ</code> en <code>ProjectmoeilijkZ</code> verklaren 43% van de variantie in ‘Interest.naZ’. Het gaat dus om een sterk effect dat bovendien mag worden doorgetrokken naar de populatie (R2 = 0.44, p &lt; 0.05). Het intercept is niet statistisch significant (p &gt; 0.05). Een leerling die gemiddeld scoort op <code>ProjectinteressantZ</code>, <code>Interest.voorZ</code>, <code>ProjectbijgeleerdZ</code> en <code>ProjectmoeilijkZ</code> scoort dus ook gemiddeld op <code>Interest.naZ</code> in de populatie. Zowel <code>ProjectinteressantZ</code> als <code>Interest.voorZ</code> hebben een positief en statistisch significant (p &lt; 0.05) effect op <code>Interest.naZ</code>. Een toename van 1 SD in <code>ProjectinteressantZ</code> leidt tot een toename van 0.19 SD in <code>Interest.naZ</code>. Het effect van <code>Interest.voorZ</code> is sterker (ß = 0.58). 1 SD hoger scoren op interesse in techniek voor het project (<code>Interest.voorZ</code>) leidt tot een toename van 0.58 SD in interesse in techniek na het project (<code>Interest.naZ</code>). De invloed van <code>ProjectmoeilijkZ</code> op <code>Interest.naZ</code> is negatief en statistisch significant (p &lt; 0.05). Leerlingen die het project als 1 SD moeilijker ervaren, scoren 0.09 SD lager op <code>Interest.naZ</code>. De percepties van leerlingen m.b.t. bijleren tijdens het project (<code>ProjectbijgeleerdZ</code>) hebben geen significante invloed op hun interesse in techniek na het project (p &gt; 0.05).</p>
</blockquote>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Gekopieerd!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Gekopieerd!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© CC-By Universiteit Antwerpen, 2024</p>
</div>   
    <div class="nav-footer-center">

<div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Wij maken gebruik van cookies om de surfervaring te verbeteren en om de website te optimaliseren. IP-adressen worden niet bewaard.</a></div></div>
    <div class="nav-footer-right">
<p>Gemaakt met veel ❤ en <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>