project:
  type: website

website:
  title: "Statistiek B"
  page-navigation: true
  reader-mode: true
  page-footer:
    right: "Gemaakt met veel ❤ en [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Universiteit Antwerpen, 2024"

  sidebar: 
    style: "docked"
    background: "#ADA601"
    foreground: "#FFFFFF"
    pinned: true
    search: true
    align: center
    border: false
    collapse-level: 1
    contents: 
      - text: "Welkom"
        href: index.qmd
        
      - section: "Open Leer Pakket"
      
      - section: "Contactmomenten"
        contents: 
          - text: "C1"
          - text: "C2"
          - text: "C3"
          - text: "C4"
          - text: "C5"
          - text: "C6"
          - text: "C7"

      - section: "Online R oefeningen"
        href: Penguins.qmd
        contents: 
          - text: "t-test"
            href: Zelftest_t_test.qmd

      - section: "ZSO"
        contents: 
          - text: "ZSO1: van vraag naar methode"
            href: ZSO/ZSO1.qmd
          - text: "ZSO2: t-test"
            href: ZSO/ZSO2.qmd
          - text: "ZSO3: ANOVA"
            href: ZSO/ZSO3.qmd
          - text: "ZSO4: Kruistabellen"
            href: ZSO/ZSO4.qmd
          - text: "ZSO5: Correlaties"
            href: ZSO/ZSO5.qmd
          - text: "ZSO6: Bivariate regressie"
            href: ZSO/ZSO6.qmd
          - text: "ZSO7: Multivariate regressie en assumpties"
            href: ZSO/ZSO7.qmd
          - text: "ZSO8: Dummy-variabelen en interacties"
            href: ZSO/ZSO8.qmd
          
      - section: "Extra materiaal"
        contents: 
          - text: "Projecten in RStudio"
            href: Extra/Projecten.qmd
          - text: "Quarto documenten"
            href: Extra/Quarto_documenten.qmd
          - text: "Data-manipulatie met dplyr"
          
      - text: "Studiewijzer"
        href: studiewijzer.qmd
    
    tools: 
      - icon: globe
        href: https://www.uantwerpen.be/nl/
        text: "uantwerpen.be/nl/"
      - icon: github
        href: https://github.com/openscapes/quarto-website-tutorial
        text: "Statistiek B"

lang: nl

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
    
editor: visual

