project:
  type: website

website:
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - deze website is nog in ontwikkeling - feedback altijd welkom via sven.demaeyer@uantwperen.be"
    type: primary
    position: above-navbar
  google-analytics: 
    tracking-id: "G-WB6XE1H6V1"
    storage: "cookies"
    anonymize-ip: true
  cookie-consent: 
   type: implied
   style: simple
   prefs-text: "Wij maken gebruik van cookies om de surfervaring te verbeteren en om de website te optimaliseren. IP-adressen worden niet bewaard."
  title: "Statistiek B"
  page-navigation: true
  reader-mode: true
  page-footer:
    right: "Gemaakt met veel ❤ en [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Universiteit Antwerpen, 2024"

  sidebar: 
    style: "docked"
    background: "#ADA601"
    foreground: "#FFFFFF"
    logo: "images/STAT B.png"
    pinned: true
    search: true
    align: center
    border: false
    collapse-level: 1
    contents: 
      - text: "Welkom"
        href: index.qmd
        
      - text: "Open Leer Pakket"
        href: OLP.qmd
      
      - section: "Contactmomenten"
        href: Contactmomenten/Contactmomenten.qmd
        contents: 
          - text: "C1"
            href: Contactmomenten/C1/C1.qmd
          - text: "C2"
            href: Contactmomenten/C2/C2.qmd
          - text: "C3"
            href: Contactmomenten/C3/C3.qmd
          - text: "C4"
            href: Contactmomenten/C4/C4.qmd
          - text: "C5"
            href: Contactmomenten/C5/C5.qmd
          - text: "C6"
            href: Contactmomenten/C6/C6.qmd
          - text: "C7"
            href: Contactmomenten/C7/C7.qmd

      - section: "Online (R) oefeningen"
        href: Penguins.qmd
        contents: 
          - text: "t-test"
            href: Zelftest_t_test.qmd
          - text: "ANOVA"
            href: Zelftest_ANOVA.qmd
          - text: "Kruistabellen"
            href: Zelftest_kruistabellen.qmd
          - text: "Correlaties"
            href: Zelftest_correlaties.qmd
            
      - text: "Computer labs"
        href: computer_labs.qmd

      - section: "ZSO"
        contents: 
          - text: "ZSO1: van vraag naar methode"
            href: ZSO/ZSO1.qmd
          - text: "ZSO2: t-test"
            href: ZSO/ZSO2.qmd
          - text: "ZSO3: ANOVA"
            href: ZSO/ZSO3.qmd
          - text: "ZSO4: Kruistabellen"
            href: ZSO/ZSO4.qmd
          - text: "ZSO5: Correlaties"
            href: ZSO/ZSO5.qmd
          - text: "ZSO6: Bivariate regressie"
            href: ZSO/ZSO6.qmd
          - text: "ZSO7: Multivariate regressie en assumpties"
            href: ZSO/ZSO7.qmd
          - text: "ZSO8: Dummy-variabelen en interacties"
            href: ZSO/ZSO8.qmd
            
      - section: "Rapporteren"
        href: Rapporteren.qmd
        contents: 
          - text: "t-test rapporteren"
            href: t_test_Rapportage.qmd
          - text: "ANOVA rapporteren"
            href: ANOVA_Rapportage.qmd
            
      - text: "Screencasts"
        href: Screencasts.qmd
        
      - section: "Extra materiaal"
        contents: 
          - text: "Projecten in RStudio"
            href: Extra/Projecten.qmd
          - text: "Quarto documenten"
            href: Extra/Quarto_documenten.qmd
          - text: "Data-manipulatie met dplyr"
          
      - text: "Studiewijzer"
        href: studiewijzer.qmd
    
    tools: 
      - icon: globe
        href: https://www.uantwerpen.be/nl/
        text: "uantwerpen.be/nl/"
      - icon: github
        href: https://github.com/Sdemaeyer2/STATB_2425
        text: "Statistiek B"

lang: nl

format:
  html:
    theme: [cosmo, theme.scss]
    mainfont: "Atkinson Hyperlegible"
    toc: true
    code-copy: true
    code-overflow: wrap
    
