---
title: "t-test zelftoetsing"
format: live-html
engine: knitr
---

{{< include ./_extensions/r-wasm/live/_knitr.qmd >}}

In wat volgt staan een aantal interactieve oefeningen die je kan doorlopen om te testen of je de materie aangaande t-testen voldoende onder de knie hebt. 

Om de oefeningen te kunnen uitvoeren hebben we de dataset `penguins` nodit uit het pakket `palmerpenguins`. Volgende code loopt automatisch zodanig dat je meteen aan de oefeningen kan beginnen!

```{webr}
#| autorun: true
#| runbutton: false
library(palmerpenguins)
data("penguins")
```

```{webr}
#| autorun: true
#| runbutton: false
#| include: false

d = function(Y,X){
	data<-na.omit(data.frame(Y,X))
	laagste<-data$X[rank(data$X)==rank(data$X)[order(rank(data$X))][2]][1] 
	hoogste<-data$X[rank(data$X)==rank(data$X)[order(rank(data$X),decreasing = TRUE)][2]][1] 
	teller=mean(data$Y [which (data$X==laagste)], na.rm=TRUE)- mean(data$Y [which (data$X==hoogste)], na.rm=TRUE)
	noemer=(sd(data$Y [which (data$X==laagste)], na.rm=TRUE) + sd(data$Y [which (data$X==hoogste)], na.rm=TRUE))/2
	teller/noemer
	}

dpaired=function(Y,X){
	teller=Y
	noemer=sqrt(X)
	teller/noemer
}

# moved from Rcmdr 13 July 2004

# levene.test.default function slightly modified and generalized from Brian Ripley via R-help
# the original generic version was contributed by Derek Ogle
# last modified 2019-02-01 by J. Fox

leveneTest <- function (y, ...) {
	UseMethod("leveneTest") 
}

leveneTest.default <- function (y, group, center=median, ...) { # original levene.test
	if (!is.numeric(y)) 
		stop(deparse(substitute(y)), " is not a numeric variable")
	if (!is.factor(group)) {
		warning(deparse(substitute(group)), " coerced to factor.")
		group <- as.factor(group)
	}
	valid <- complete.cases(y, group)
	meds <- tapply(y[valid], group[valid], center, ...)
	resp <- abs(y - meds[group])
	table <- anova(lm(resp ~ group))[, c(1, 4, 5)]
	rownames(table)[2] <- " "
	dots <- deparse(substitute(...))
	attr(table, "heading") <- paste("Levene's Test for Homogeneity of Variance (center = ", 
			deparse(substitute(center)), if(!(dots == "NULL")) paste(":", dots),  ")", sep="")
	table
}


leveneTest.formula <- function(y, data, ...) {
	form <- y
	mf <- if (missing(data)) model.frame(form) else model.frame(form, data)
	if (any(sapply(2:dim(mf)[2], function(j) is.numeric(mf[[j]])))) 
		stop("Levene's test is not appropriate with quantitative explanatory variables.")
	y <- mf[,1]
	if(dim(mf)[2]==2) group <- mf[,2]
	else {
		if (length(grep("\\+ | \\| | \\^ | \\:",form))>0) stop("Model must be completely crossed formula only.")
		group <- interaction(mf[,2:dim(mf)[2]])
	}
	leveneTest.default(y=y, group=group, ...)
}


leveneTest.lm <- function(y, ...) {
    m <- model.frame(y)
    m$..y <- model.response(m)
    f <- formula(y)
    f[2] <- expression(..y)
	leveneTest.formula(f, data=m, ...)
}
```

Meer achtergrond over deze dataset vind je via volgende link: [palmerpenguins](Penguins.qmd)

## Oefening 1

We zijn geïnteresseerd in verschillen tussen mannelijk en vrouwelijke pinguïns. Meerbepaald zijn we benieuwd wat het verschil in lichaamsmassa (`body_mass_g`) is tussen beide sekses (`sex`).

*Vul onderstaande code aan om de gemiddeldes per sekse te berekenen.*

::: {.panel-tabset}

## Oefening

```{webr}
#| exercise: ex1
#| caption: Oefening1

tapply(penguins$body_mass_g, _______ , _______)
```

```{webr}
#| exercise: ex1
#| check: true
answer <- tapply(penguins$body_mass_g, penguins$sex , mean)
if (identical(.result, answer)) {
  list(correct = TRUE, message = "Juist!")
} else {
  list(correct = FALSE, message = "Fout.")
}
```

## Hints

::: { .hint exercise="ex1" }
We willen het gemiddelde per categorie van de variabele `penguins$sex` berekenen. Dus, je moet in je code iets met die variabele doen.

```r
tapply(penguins$body_mass_g, penguins$____ , _____)
```
:::

::: { .hint exercise="ex1" }
Als je die variabele mee opgenomen hebt in je code, moet je nog tegen R zeggen wat precies berekend moet worden. Hier gaat het om het gemiddelde berekenen. Welke functie in `R` kan je hanteren om het gemiddelde te berekenen?

```r
tapply(penguins$body_mass_g, penguins$sex , _____)
```
:::

## Oplossing
::: { .solution exercise="ex1" }

**Oplossing:**

De volledige oplossing ziet er zo uit!

```{webr}
#| exercise: ex1
#| solution: true
tapply(penguins$body_mass_g, penguins$sex , mean)
```

:::
:::

## Oefening 2

In de eerste oefening kregen we zicht op de gemiddelde lichaamsmassa van mannelijke en vrouwelijke pinguïns in de steekproef. Uiteraard zijn we meer geïnteresseerd in hoe dit in de populatie zit! We wensen dus een t-test uit te voeren. 

*Voer in het onderstaande code blok de juiste code in om de t-test uit te voeren (je mag er even vanuit gaan dat er voldaan is aan de assumptie van gelijke varianties).*

::: {.panel-tabset}

## Oefening

```{webr}
#| exercise: ex2
#| caption: Oefening2


```

```{webr}
#| exercise: ex2
#| check: true
answer <- t.test(penguins$body_mass_g ~penguins$sex)
if (identical(.result, answer)) {
  list(correct = TRUE, message = "Juist!")
} else {
  list(correct = FALSE, message = "Fout.")
}
```

## Hints

::: { .hint exercise="ex2" }
We willen een t-test uitvoeren. Daartoe maak je best gebruik van de functie `t.test( )`. 

```r
t.test(______ ~ _______)
```

:::

## Oplossing
::: { .solution exercise="ex2" }

**Oplossing:**

De volledige oplossing ziet er zo uit!

```{webr}
#| exercise: ex2
#| solution: true
t.test(penguins$body_mass_g ~ penguins$sex)
```

:::
:::

## Oefening 3

Met de t-test zijn we nagegaan of we statistische evidentie hebben dat het verschil in gemiddelden in de steekproef ook kan worden veralgemeend naar een verschil in de populatie van alle pinguïns. We zijn dus de statistische significantie nagegaan. Echter, het resultaat van zo'n test is afhankelijk van de steekproefgrootte. Om een algemeen beeld te krijgen over hoe groot het verschil is tussen beide groepen introduceren we het idee van effectgrootte.

*Doe de nodige analyse om tevens de effectgrootte na te gaan voor het verschil in lichaamsmasse tussen mannelijke en vrouwelijke pinguïns* 

::: {.panel-tabset}

## Oefening

```{webr}
#| exercise: ex3
#| caption: Oefening3


```

```{webr}
#| exercise: ex3
#| check: true
answer <- d(penguins$body_mass_g, penguins$sex)
if (identical(.result, answer)) {
  list(correct = TRUE, message = "Juist!")
} else {
  list(correct = FALSE, message = "Fout.")
}
```

## Hints

::: { .hint exercise="ex3" }
We willen Cohen's d berekenen om de effectgrootte uit te drukken. Daartoe maak je best gebruik van de functie `d( )`. 

```r
d(______ , _______)
```

:::

## Oplossing
::: { .solution exercise="ex3" }

**Oplossing:**

De volledige oplossing ziet er zo uit!

```{webr}
#| exercise: ex3
#| solution: true

d(penguins$body_mass_g, penguins$sex)
```

:::
:::

## Oefening 4

In oefening 2 hebben we abstractie gemaakt van de assumptie van gelijke binnen-groepen varianties voor beide sekses. 

*Test nu de assumptie dat beide varianties gelijk zijn. Is het zo dat de variantie in lichaamsmassa voor mannelijke pinguïns vergelijkbaar is met de variantie in lichaamsmassa voor vrouwelijke pinguïns?*

::: {.panel-tabset}

## Oefening

```{webr}
#| exercise: ex4
#| caption: Oefening4


```

```{webr}
#| exercise: ex4
#| check: true
answer <- leveneTest(penguins$body_mass_g, penguins$sex)
if (identical(.result, answer)) {
  list(correct = TRUE, message = "Juist!")
} else {
  list(correct = FALSE, message = "Fout.")
}
```

## Hints

::: { .hint exercise="ex4" }
Om deze assumptie na te gaan dienen we een **Levene test** uit te voeren. 

```r
leveneTest(_____, _______)
```

:::

## Oplossing
::: { .solution exercise="ex4" }

**Oplossing:**

De volledige oplossing ziet er zo uit!

```{webr}
#| exercise: ex4
#| solution: true

leveneTest(penguins$body_mass_g, penguins$sex)
```

:::
:::

## Oefening 5

Nu je meer zicht hebt op het feit dat de assumptie van gelijke varianties niet op gaat, betekent dit dat we de t-test opnieuw moeten uitvoeren adhv een andere functie. 

*Voer de t-test opnieuw uit met de gepaste toets en functie in R.*

::: {.panel-tabset}

## Oefening

```{webr}
#| exercise: ex5
#| caption: Oefening5


```

```{webr}
#| exercise: ex5
#| check: true
answer <- t.test(penguins$body_mass_g ~ penguins$sex, var.equal = FALSE)
if (identical(.result, answer)) {
  list(correct = TRUE, message = "Juist!")
} else {
  list(correct = FALSE, message = "Fout.")
}
```

## Hints

::: { .hint exercise="ex5" }
Hiertoe moeten we de functie `t.test( )` uitbreiden met een extra argument dat aan `R` meegeeft dat de assumptie van gelijke varianties niet opgaat. 

```r
t.test(penguins$body_mass_g ~ penguins$sex, _____)
```

:::

## Oplossing
::: { .solution exercise="ex4" }

**Oplossing:**

De volledige oplossing ziet er zo uit!

```{webr}
#| exercise: ex5
#| solution: true

t.test(penguins$body_mass_g ~ penguins$sex, var.equal = FALSE)
```

:::
:::


## Oefening 6

De nodige analyses zijn uitgevoerd. Wat nu nog rest is het goed interpreteren en uitschrijven van conclusies op basis van de output die gegenereerd is tijdens de analyses.

*Schrijf voor jezelf een alinea waarin je de nodige informatie opneemt om de resultaten van de analyse te communiceren.*

::: { .callout-tip title="Oplossing" collapse="true"}
Dit is een mogelijke verwoording van de resultaten;

*In de steekproef van onderzochte pinguïns stellen we vast dat vrouwelijke pinguïns een lagere gemiddelde lichaamsmassa hebben (gemiddelde = 3862 gram) dan  de mannelijke pinguïns (gemiddelde = 4546 gram). Dit verschil in lichaamsmassa tussen vrouwelijke en mannelijke pinguïns is statistisch significant (t = -8.55, df = 323.9, p <0.001). Met andere woorden, de kans dat we dit verschil in lichaamsmassa vaststellen in onze steekproef indien er in de gehele populatie geen verschil zou zijn, is bijzonder laag. We concluderen dus dat er voldoende evidentie is om te stellen dat vrouwelijke pinguïns een lagere lichaamsmassa hebben dan de mannelijke pinguïns. Uit de effectgrootte (Cohen's d = -0.94) kunnen we afleiden dat dit gezien kan worden als een groot verschil.*
:::

