<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ZSO 7 – Statistiek B</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../ZSO/ZSO8.html" rel="next">
<link href="../ZSO/ZSO6.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Geen resultaten",
    "search-matching-documents-text": "Gevonden documenten",
    "search-copy-link-title": "Kopieer link om te zoeken",
    "search-hide-matches-text": "Extra overeenkomsten verbergen",
    "search-more-match-text": "meer overeenkomst in dit document",
    "search-more-matches-text": "meer overeenkomsten in dit document",
    "search-clear-button-title": "Wissen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuleren",
    "search-submit-button-title": "Verzenden",
    "search-label": "Zoeken"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../ZSO/ZSO1.html">ZSO</a></li><li class="breadcrumb-item"><a href="../ZSO/ZSO7.html">ZSO7: Multivariate regressie en assumpties</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Zoeken" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../images/STAT B.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main tools-wide">
    <a href="https://www.uantwerpen.be/nl/" title="uantwerpen.be/nl/" class="quarto-navigation-tool px-1" aria-label="uantwerpen.be/nl/"><i class="bi bi-globe"></i></a>
    <a href="https://github.com/openscapes/quarto-website-tutorial" title="Statistiek B" class="quarto-navigation-tool px-1" aria-label="Statistiek B"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Schakel leesmodus">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Zoeken"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welkom</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Open Leer Pakket</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Contactmomenten</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
 <span class="menu-text">C1</span>
  </li>
          <li class="sidebar-item">
 <span class="menu-text">C2</span>
  </li>
          <li class="sidebar-item">
 <span class="menu-text">C3</span>
  </li>
          <li class="sidebar-item">
 <span class="menu-text">C4</span>
  </li>
          <li class="sidebar-item">
 <span class="menu-text">C5</span>
  </li>
          <li class="sidebar-item">
 <span class="menu-text">C6</span>
  </li>
          <li class="sidebar-item">
 <span class="menu-text">C7</span>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../Penguins.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Online (R) oefeningen</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Zelftest_t_test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">t-test</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">ZSO</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ZSO/ZSO1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO1: van vraag naar methode</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ZSO/ZSO2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO2: t-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ZSO/ZSO3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO3: ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ZSO/ZSO4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO4: Kruistabellen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ZSO/ZSO5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO5: Correlaties</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ZSO/ZSO6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO6: Bivariate regressie</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ZSO/ZSO7.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">ZSO7: Multivariate regressie en assumpties</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ZSO/ZSO8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO8: Dummy-variabelen en interacties</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../Rapporteren.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Rapporteren</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../t_test_Rapportage.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">t-test rapporteren</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Extra materiaal</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Extra/Projecten.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Projecten in RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Extra/Quarto_documenten.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quarto documenten</span></a>
  </div>
</li>
          <li class="sidebar-item">
 <span class="menu-text">Data-manipulatie met dplyr</span>
  </li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../studiewijzer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Studiewijzer</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Op deze pagina</h2>
   
  <ul>
  <li><a href="#opdrachten" id="toc-opdrachten" class="nav-link active" data-scroll-target="#opdrachten">OPDRACHTEN</a></li>
  <li><a href="#responsen" id="toc-responsen" class="nav-link" data-scroll-target="#responsen">RESPONSEN</a>
  <ul class="collapse">
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section">1.1</a></li>
  <li><a href="#section-1" id="toc-section-1" class="nav-link" data-scroll-target="#section-1">1.2</a></li>
  <li><a href="#section-2" id="toc-section-2" class="nav-link" data-scroll-target="#section-2">1.3</a></li>
  <li><a href="#section-3" id="toc-section-3" class="nav-link" data-scroll-target="#section-3">1.4</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Andere formaten</h2><ul><li><a href="ZSO7.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../ZSO/ZSO1.html">ZSO</a></li><li class="breadcrumb-item"><a href="../ZSO/ZSO7.html">ZSO7: Multivariate regressie en assumpties</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">ZSO 7</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="opdrachten" class="level1 unnumbered">
<h1 class="unnumbered">OPDRACHTEN</h1>
<p>Het databestand bevat de gegevens van de lerarenbevraging uit de ‘Civic Education Study’. Deze studie is een internationale studie naar burgerschapsopvoeding (vergelijkbaar met PISA onderzoek, maar dan over een ander onderwerp). Daarbij werden zowel 14-jarigen als leraren en schoolhoofden in verschillende landen over dit thema bevraagd.</p>
<p>Concreet bevat dit bestand een selectie van de gegevens uit de leerkrachtenbevraging. Meerbepaald bevat het bestand o.a. de volgende variabelen:</p>
<p>-‘Ondmeth1’: burgerschapsopvoeding als afzonderlijk vak; -‘Onderwijservaring’: aantal jaren onderwijservaring; -‘ErvaringBO’: aantal jaren ervaring in het geven van burgerschapsopvoeding; -‘DiplomaBO’: respondent heeft een diploma in een discipline die gerelateerd is aan burgerschapsopvoeding; -‘NavormBO’: respondent heeft navorming genoten in een discipline die gerelateerd is aan burgerschapsopvoeding; -‘Leeftijd’: leeftijd van de leraar (als continue variabele); -‘Leeftijd6’: leeftijd van de leraar (ingedeeld in 6 categorieën); -‘Belang’: belang dat gehecht wordt aan het geven van kennisinhouden bij burgerschapsopvoeding; -‘Zelfver’: zelfvertrouwen in het geven van kennisinhouden bij burgerschapsopvoeding.</p>
<p>Er bestaan verschillende psychologische theorieën die stellen dat een persoon voornamelijk belang hecht aan zaken waarvan hij of zij ook zeker is dat hij of zij ze kan uitvoeren. Als we dit toepassen op deze data, dan kan je veronderstellen dat zelfvertrouwen in het geven van kennisinhouden aangaande burgerschapsopvoeding bij leerkrachten (‘Zelfver’) een goede voorspeller is van het belang dat leerkrachten hechten aan het geven van kennisinhouden (‘Belang’).</p>
<p>In de onderzoeksgroep waar je werkt stelt iemand anders dat het veel eerder te maken heeft met onderwijservaring (‘Onderwijservaring’). Hij veronderstelt dat, als iemand al lang in het onderwijs staat, dat die persoon dan ook meer en meer het belang gaat inzien om bij jongeren expliciet onderwijs te geven aangaande burgerschapsopvoeding (‘Belang’).</p>
<p><em>1.1 Je zit dus met 2 hypothesen. Je wil deze hypothesen in 2 afzonderlijke analyses toetsen. Voor zelfvertrouwen maak je gebruik van de variabele ‘Zelfver’. Om het effect van het onderwijservaring na te gaan maak je gebruik van de variabele ‘Onderwijservaring’. Aan de hand van welke onderzoekstechniek zou je beide hypothesen afzonderlijk testen en waarom?</em></p>
<p><em>1.2 Toets beide hypothesen. Welke conclusies kan je trekken? Wees hierbij zo volledig mogelijk. Kan je deze doortrekken naar de gehele populatie? Van welke variabele kan je zeggen dat die het sterkste een invloed uitoefent op de variabele ‘Belang’?</em></p>
<p><em>1.3 We hebben in de dataset de volgende variabelen: ‘Belang’, ‘Zelfver’, ‘ErvaringBO’ en ‘Onderwijservaring’ (aantal jaren onderwijservaring). Teken het onderzoekschema dat bij de volgende onderzoeksvraag past: Is het zo dat het belang dat leerkrachten hechten aan het geven van kennisinhouden bij het vak burgerschapsopvoeding beïnvloed wordt door het zelfvertrouwen, nadat je controleert voor zowel het aantal jaren onderwijservaring in het algemeen als het aantal jaren ervaring in het geven van burgerschapsopvoeding specifiek? Welke onderzoekstechniek hoort hierbij?</em></p>
<p><em>1.4 Voer de analyse uit die je in 1.3 suggereerde? Vooraleer je dit doet, ga je eerst na of dit wel gepast is. Interpreteer vervolgens de resultaten van de analyse zelf.</em></p>
<p>[RESPONS ACHTERAAN DOCUMENT] </p>
</section>
<section id="responsen" class="level1 unnumbered">
<h1 class="unnumbered">RESPONSEN</h1>
<p>Vooraleer we de analyses kunnen uitvoeren moeten we uiteraard de data inladen in <code>R</code> en tevens de OLP2 Functies activeren. Dit doen we bijvoorbeeld door gebruk te maken van de commando’s <code>load( )</code> en <code>source( )</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"CivedZSO7.RData"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"OLP2 Functies.R"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="section" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="section">1.1</h2>
<p>Beide hypothesen gaan over het causale effect van één kwantitatieve variabele op een andere kwantitatieve variabele. Daarom kunnen we voor elk van beide hypothesen gebruik maken van een bivariate regressieanalyse.</p>
</section>
<section id="section-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="section-1">1.2</h2>
<ol type="a">
<li>Analyses + bespreking resultaten aangaande Zelfvertrouwen</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>Model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Belang <span class="sc">~</span> Zelfver, <span class="at">data =</span> CivedZSO7)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Model1)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Belang ~ Zelfver, data = CivedZSO7)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.55780 -0.23645  0.01354  0.22793  1.19233 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  2.55760    0.03794   67.41   &lt;2e-16 ***
Zelfver      0.25007    0.01275   19.61   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3448 on 2135 degrees of freedom
  (349 observations deleted due to missingness)
Multiple R-squared:  0.1527,    Adjusted R-squared:  0.1523 
F-statistic: 384.7 on 1 and 2135 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Uit deze analyse blijkt dat 15.23% (Adj. <span class="math inline">\(R^2\)</span> = 0.1523) van de verschillen in het belang dat leerkrachten hechten aan kennisinhoud (‘Belang’) toe te schrijven zijn aan verschillen in zelfvertrouwen om effectief kennisinhouden te onderwijzen (‘Zelfver’). Het gaat dus om een groot effect (zie vuistregels van Cohen). Op basis van de F-test (<em>F</em>(1,2135) = 384.7, <em>p</em> &lt; 0.001) leren we bovendien dat ‘Zelfver’ ook in de gehele populatie van leerkrachten een deel van de variantie in ‘Belang’ zou verklaren. Het model is m.a.w. statistisch significant.</p>
<p>Het intercept geeft aan dat een leerkracht met een score 0 op de schaal ‘Zelfver’, 2.558 zou scoren op de schaal ‘Belang’. Per punt dat een leerkracht hoger scoort op ‘Zelfver’ stijgt de score op ‘Belang’ met 0.25 punten. Zowel het intercept (<span class="math inline">\(\beta_0\)</span> = 2.558, <em>p</em> &lt; 0.001) als de hellingsgraad (<span class="math inline">\(\beta_1\)</span> = 0.25, <em>p</em> &lt; 0.001) zijn bovendien statistisch significant. De kans dat het intercept en de hellingsgraad 0 zouden bedragen is zo klein dat we ervan uitgaan dat we ook in de populatie een gelijkaardig intercept en hellingsgraad zouden vaststellen. </p>
<ol start="2" type="a">
<li>Analyses + bespreking resultaten aangaande Onderwijservaring</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>Model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Belang <span class="sc">~</span> Onderwijservaring, <span class="at">data =</span> CivedZSO7)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Model2)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Belang ~ Onderwijservaring, data = CivedZSO7)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.60502 -0.27632  0.00632  0.27054  0.78816 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        3.3377295  0.0158758 210.241  &lt; 2e-16 ***
Onderwijservaring -0.0030705  0.0008003  -3.836 0.000128 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3752 on 2196 degrees of freedom
  (288 observations deleted due to missingness)
Multiple R-squared:  0.006658,  Adjusted R-squared:  0.006205 
F-statistic: 14.72 on 1 and 2196 DF,  p-value: 0.0001283</code></pre>
</div>
</div>
<p>Hoewel de F-toets (<em>F</em>(1,2196) = 14.72, <em>p</em> &lt; 0.001) aangeeft dat het model statistisch significant afwijkt aandeel van variantie verklaard, is de verklaarde variantie verwaarloosbaar klein (Adj. <span class="math inline">\(R^2\)</span> = 0.006). De variabele ‘Onderwijservaring’ zal dus in de gehele populatie ook een deel van de verschillen in ‘Belang’ verklaren, maar dit effect is zo klein dat het van weinig praktische waarde is.</p>
<p>Hoewel het model weinig verschillen verklaart in ‘Belang’ blijken zowel het intercept als de slope voor ‘Onderwijservaring’ statistisch significant af te wijken van 0. Ook hier kunnen we de conclusies op basis van de steekproefgevens dus doortrekken naar de populatie. Uit het intercept lezen we af dat een leerkracht met nul jaren onderwijservaring 3.338 (<em>p</em> &lt; 0.001) zou scoren op belang gehecht aan kennisinhouden (‘Belang’). Naarmate een leerkracht meer onderwijservaring heeft, daalt dit belang gehecht aan kennisinhouden: per jaar meer ervaring daalt de verwachte score voor ‘Belang’ met 0.003 eenheden (<span class="math inline">\(\beta_1\)</span> = -0.003, <em>p</em> &lt; 0.001). De relatie tussen ‘Onderwijservaring’ en ‘Belang’ is dus negatief.</p>
<p>Om na te gaan welke variabele het meeste invloed uitoefent op ‘Belang’, vergelijken we de <span class="math inline">\(R^2\)</span> van beide analyses. Hieruit blijkt dat de variabele ‘Zelfver’ duidelijk een sterkere invloed heeft op ‘Belang’ dan de variabele ‘Onderwijservaring’. Die laatste variabele verklaart immers slechts 0.62% (Adj <span class="math inline">\(R^2\)</span> = 0.0062, <em>p</em> &lt; 0.001) van de verschillen in ‘Belang’ wat vergeleken met de 15,23% verklaarde variantie (Adj <span class="math inline">\(R^2\)</span> = 0.1523, <em>p</em> &lt; 0.001) door de variabele ‘Zelfver’ een pak lager is. </p>
</section>
<section id="section-2" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="section-2">1.3</h2>
<p>De visualisatie ziet er als volgt uit:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ZSO7_figuur1_3.jpg" class="img-fluid figure-img" width="400"></p>
</figure>
</div>
</div>
</div>
<p>Dit vraagt om een <strong>meervoudige regressieanalyse</strong>.</p>
</section>
<section id="section-3" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="section-3">1.4</h2>
<ol type="a">
<li>Analyses assumpties bij regressieanalyse</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>Model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Belang <span class="sc">~</span> Zelfver <span class="sc">+</span> ErvaringBO <span class="sc">+</span> Onderwijservaring, <span class="at">data =</span> CivedZSO7)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Model3)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ZSO7_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">residuals_plot</span>(Model3)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Residuals_plotZSO7.jpeg" class="img-fluid figure-img" width="350"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cooks_plot</span>(Model3)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Cook_PlotZSO7.jpeg" class="img-fluid figure-img" width="350"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(Model3)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Zelfver        ErvaringBO Onderwijservaring 
         1.010080          4.015503          3.999973 </code></pre>
</div>
</div>
<ol start="2" type="a">
<li>Resultaten bespreken met verwijzing naar output</li>
</ol>
<p>De plot linksboven (Residuals versus Fitted) geeft aan dat er aan de assumpties m.b.t. lineariteit, homoscedasticiteit en afwezigheid van clustering is voldaan. De Scale-location plot bevestigt de vaststelling inzake heteroscedasticiteit (de variantie in residuelen is onafhankelijk van de y-waarden) en afwezigheid van clustering. Het ‘vreemde’ patroon in de ‘Scale-location plot’ is een gevolg van het gebruik van discrete variabelen in het model. Discrete variabelen zijn variabelen waarbij er geen tussenliggende waarden zijn (bv. aantal jaren onderwijservaring: het gaat om 1, 2, 3 of… jaar, maar niet om 1.22 jaar onderwijservaring). Uit de QQ-plot blijkt dat de errortermen bij benadering normaal verdeeld zijn. Alle punten vallen immers min of meer op de rechte.</p>
<p>Om na te gaan of er outliers zijn die de resultaten van de regressieanalyse kunnen vertekenen, baseren we ons op de studentized residuals en op Cook’s distance. Uit de studentized residuals leren we dat voornamelijk leerkrachten op rijen 1417 (onderaan figuur, cijfers vallen wat weg), 345 en 1362 een te sterke invloed hebben op de parameterschattingen. We zouden kunnen overwegen om die drie alvast weg te laten. Het Cook’s distance criterium bevestigt de impact van zowel de leerkrachten op rij 345 en op rij 1417. Beiden vallen opnieuw buiten de grenzen van wat aanvaardbaar is. Er is m.a.w. evidentie om deze gevallen uit de analyse te verwijderen en vervolgens de analyse opnieuw uit te voeren.</p>
<p>Ten slotte wordt de assumpties inzake multicollineaireit getoetst aan de hand van de VIF-waarden. Uit de analyses blijkt dat de VIF’s voor de verschillende onafhankelijke variabelen niet boven de grenswaarde van 5 uitkomt. Er is dus geen probleem van multicollineariteit.</p>
<ol start="3" type="a">
<li>Analyses meervoudige regressie</li>
</ol>
<p>Vooraleer de eigenlijk analyse uit te voeren, maken we een nieuw databestand aan zonder de rijen 345 en 1417 (outliers). In principe zouden we de assumpties nu opnieuw kunnen nagegaan en indien nodig verdere outliers verwijderen. We werken echter verder op dit databestand.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># databestand maken zonder rij 345 en rij 1417</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>CivedZSO7_bis <span class="ot">&lt;-</span> CivedZSO7[<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">344</span>, <span class="dv">346</span><span class="sc">:</span><span class="dv">1416</span>, <span class="dv">1418</span><span class="sc">:</span><span class="dv">2486</span>), ] </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Model opnieuw schatten op de nieuw aangemaakte data</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>Model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Belang <span class="sc">~</span> Zelfver <span class="sc">+</span> ErvaringBO <span class="sc">+</span> Onderwijservaring, <span class="at">data=</span>CivedZSO7_bis)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Model3)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Belang ~ Zelfver + ErvaringBO + Onderwijservaring, 
    data = CivedZSO7_bis)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.48846 -0.25172 -0.00118  0.23370  0.96304 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        2.567087   0.041794  61.422   &lt;2e-16 ***
Zelfver            0.262839   0.013357  19.679   &lt;2e-16 ***
ErvaringBO        -0.001138   0.001604  -0.710    0.478    
Onderwijservaring -0.001978   0.001540  -1.285    0.199    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.343 on 2022 degrees of freedom
  (458 observations deleted due to missingness)
Multiple R-squared:  0.1654,    Adjusted R-squared:  0.1641 
F-statistic: 133.5 on 3 and 2022 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ol start="4" type="a">
<li>Resultaten bespreken met verwijzing naar output</li>
</ol>
<p>Zelfvertrouwen (‘Zelfver’), het aantal jaren ervaring in burgerschapsopvoeding (‘ErvaringBO’) en het aantal jaren onderwijservaring (‘Onderwijservaring’ ) verklaren samen 16.41% (Adj. <span class="math inline">\(R^2\)</span> = 0.1641, <em>p</em> &lt; 0.001) van de variantie in belang gehecht aan kennisinhouden (‘Belang’). De F-test (<em>F</em>(3,2022) = 133.5, <em>p</em> &lt; 0.001) leert bovendien dat in de populatie deze drie variabelen samen ook een deel van de verschillen in de afhankelijke variabele zouden verklaren.</p>
<p>Uit het intercept blijkt dat een leerkracht die 0 scoort op de drie onafhankelijke variabelen, een score van 2.567 behaalt op ‘Belang’ (<span class="math inline">\(\beta_0\)</span> = 2.567, <em>p</em> &lt; 0.001). De overige parameterschattingen geven aan dat er enkel een statistisch significant effect is van zelfvertrouwen (‘Zelfver’): één punt hoger scoren op ‘Zelfver’ leidt tot 0.263 punten hoger scoren op ‘Belang’ (<span class="math inline">\(\beta_1\)</span> = 0.263, <em>p</em> &lt; 0.001). Het gaat dus om een positief effect: hoe hoger het zelfvertrouwen van leerkrachten om kennisinhouden aan te brengen, des te meer belang gaan ze ook hechten aan die kennisinhouden. Dit effect is onafhankelijk van de ervaring van de leerkracht (al dan niet specifieke onderwijservaring voor het geven van Burgerschapsopvoeding; ‘ErvaringBO’ en ‘Onderwijservaring’). De parameterschattingen voor zowel ‘ErvaringBO’ (<span class="math inline">\(\beta_2\)</span> = -0.001, <em>p</em> = 0.478) als ‘Onderwijservaring’ (<span class="math inline">\(\beta_3\)</span> = -0.002, <em>p</em> = 0.199) zijn niet statistisch significant. Bijgevolg kunnen we niet met voldoende zekerheid stellen dat er in de populatie ook sprake zal zijn van een effect van die twee variabelen.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Gekopieerd!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Gekopieerd!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../ZSO/ZSO6.html" class="pagination-link" aria-label="ZSO6: Bivariate regressie">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">ZSO6: Bivariate regressie</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../ZSO/ZSO8.html" class="pagination-link" aria-label="ZSO8: Dummy-variabelen en interacties">
        <span class="nav-page-text">ZSO8: Dummy-variabelen en interacties</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© CC-By Universiteit Antwerpen, 2024</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Gemaakt met veel ❤ en <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>