<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ZSO 8 – Statistiek B</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../Rapporteren.html" rel="next">
<link href="../ZSO/ZSO7.html" rel="prev">
<script src="../site_libs/cookie-consent/cookie-consent.js"></script>
<link href="../site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-b86774849c83f8842429632de05d13be.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Geen resultaten",
    "search-matching-documents-text": "Gevonden documenten",
    "search-copy-link-title": "Kopieer link om te zoeken",
    "search-hide-matches-text": "Extra overeenkomsten verbergen",
    "search-more-match-text": "meer overeenkomst in dit document",
    "search-more-matches-text": "meer overeenkomsten in dit document",
    "search-clear-button-title": "Wissen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuleren",
    "search-submit-button-title": "Verzenden",
    "search-label": "Zoeken"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-WB6XE1H6V1"></script>

<script type="text/plain" cookie-consent="tracking">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-WB6XE1H6V1', { 'anonymize_ip': true});
</script>

<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"simple",
  "consent_type":"implied",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary","functionality","tracking","targeting"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  ,
"language":"nl"
  });
});
</script> 
  

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <div id="quarto-announcement" data-announcement-id="b0e362a38869e05bc3e01903c80d0932" class="alert alert-primary hidden"><i class="bi bi-info-circle quarto-announcement-icon"></i><div class="quarto-announcement-content">
<p><strong>Alert</strong> - deze website is nog in ontwikkeling - feedback altijd welkom via sven.demaeyer@uantwperen.be</p>
</div><i class="bi bi-x-lg quarto-announcement-action"></i></div>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../ZSO/ZSO1.html">ZSO</a></li><li class="breadcrumb-item"><a href="../ZSO/ZSO8.html">ZSO8: Dummy-variabelen en interacties</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Schakel zijbalknavigatie" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Zoeken" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../images/STAT B.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main tools-wide">
    <a href="https://www.uantwerpen.be/nl/" title="uantwerpen.be/nl/" class="quarto-navigation-tool px-1" aria-label="uantwerpen.be/nl/"><i class="bi bi-globe"></i></a>
    <a href="https://github.com/Sdemaeyer2/STATB_2425" title="Statistiek B" class="quarto-navigation-tool px-1" aria-label="Statistiek B"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Schakel leesmodus">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Zoeken"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welkom</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../OLP.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Open Leer Pakket</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../Contactmomenten/Contactmomenten.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Contactmomenten</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Contactmomenten/C1/C1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">C1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Contactmomenten/C2/C2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">C2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Contactmomenten/C3/C3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">C3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Contactmomenten/C4/C4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">C4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Contactmomenten/C5/C5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">C5</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Contactmomenten/C6/C6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">C6</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Contactmomenten/C7/C7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">C7</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../Penguins.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Online (R) oefeningen</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Zelftest_t_test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">t-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Zelftest_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Zelftest_kruistabellen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Kruistabellen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Zelftest_correlaties.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Correlaties</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Zelftest_bivariate_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bivariate regressie</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../computer_labs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Computer labs</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">ZSO</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ZSO/ZSO1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO1: van vraag naar methode</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ZSO/ZSO2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO2: t-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ZSO/ZSO3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO3: ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ZSO/ZSO4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO4: Kruistabellen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ZSO/ZSO5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO5: Correlaties</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ZSO/ZSO6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO6: Bivariate regressie</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ZSO/ZSO7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO7: Multivariate regressie en assumpties</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ZSO/ZSO8.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">ZSO8: Dummy-variabelen en interacties</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../Rapporteren.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Rapporteren</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../t_test_Rapportage.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">t-test rapporteren</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ANOVA_Rapportage.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ANOVA rapporteren</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Screencasts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Screencasts</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Extra materiaal</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Schakel sectie">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Extra/Projecten.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Projecten in RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Extra/Quarto_documenten.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quarto documenten</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Extra/dplyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">dplyr en tidyr</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../studiewijzer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Studiewijzer</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Op deze pagina</h2>
   
  <ul>
  <li><a href="#voorbereiding" id="toc-voorbereiding" class="nav-link active" data-scroll-target="#voorbereiding">Voorbereiding</a></li>
  <li><a href="#opdrachten" id="toc-opdrachten" class="nav-link" data-scroll-target="#opdrachten">OPDRACHTEN</a></li>
  <li><a href="#responsen" id="toc-responsen" class="nav-link" data-scroll-target="#responsen">RESPONSEN</a>
  <ul class="collapse">
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section">1.1</a></li>
  <li><a href="#section-1" id="toc-section-1" class="nav-link" data-scroll-target="#section-1">1.2</a></li>
  <li><a href="#section-2" id="toc-section-2" class="nav-link" data-scroll-target="#section-2">1.3</a></li>
  <li><a href="#section-3" id="toc-section-3" class="nav-link" data-scroll-target="#section-3">1.4</a></li>
  <li><a href="#section-4" id="toc-section-4" class="nav-link" data-scroll-target="#section-4">1.5</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Andere formaten</h2><ul><li><a href="ZSO8.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../ZSO/ZSO1.html">ZSO</a></li><li class="breadcrumb-item"><a href="../ZSO/ZSO8.html">ZSO8: Dummy-variabelen en interacties</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">ZSO 8</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="voorbereiding" class="level1">
<h1>Voorbereiding</h1>
<p>Voor deze ZSO ga je aan de slag met de dataset: <code>DataZSO8.RData.RData</code>. De data kan je downloaden door op onderstaande link te klikken met een rechtermuisklik.</p>
<p><a href="../ZSO/DataZSO8.RData">DOWNLOAD DE DATA</a></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Een goede workflow in <code>RStudio</code> is van cruciaal belang op lange termijn. In dit vak is het geen verplichting, maar werken met projecten in <code>RStudio</code> kan je leven een pak makkelijker maken.</p>
<p>Daarom raden we je aan om een nieuw project te maken per ZSO. Concreet betekent dit dat je tevens op je pc een map maakt per ZSO met daarin alle nodige files voor die ZSO:</p>
<ul>
<li>databestanden</li>
<li><code>OLP2 functies.R</code> file</li>
<li>Je script met analyses (of Quarto document)</li>
</ul>
<p>Meer uitleg over werken met projecten en Quarto documenten kan je vinden onder Extra materiaal (<a href="../Extra/Projecten.html">KLIK HIER</a>)</p>
</div>
</div>
</section>
<section id="opdrachten" class="level1 unnumbered">
<h1 class="unnumbered">OPDRACHTEN</h1>
<p>Het databestand bevat gegevens van leerlingen in het 6de jaar secundair onderwijs. Belangrijkste doelstelling van het onderzoek waaruit deze data voortkomt, was de overgang naar hoger onderwijs verder te onderzoeken. In deze dataset maakten we een selectie van volgende variabelen:</p>
<ul>
<li><code>Leerlingnummer</code>: een identificatienummer voor leerlingen;</li>
<li><code>Iq</code>: de score die een leerling behaalde op een IQ toets;</li>
<li><code>Begrlezen</code>: behaald percentage op een toets aangaande begrijpend lezen;</li>
<li><code>Ondvorm</code>: onderwijsvorm waarin de leerling zit (1 = ASO ; 2 = BSO ; 3 = TSO);</li>
<li><code>Demotivatiez</code>: mate van demotivatie om verder te studeren als z-score;</li>
<li><code>Willenz</code>: mate van intrinsieke motivatie om verder te studeren als z-score;</li>
<li><code>Moetenz</code>: mate van extrinsieke motivatie om verder te studeren als z-score.</li>
</ul>
<p>Je wenst grip te krijgen op welke leerlingen in meerdere of mindere mate gedemotiveerd zijn om verder te studeren. Daartoe ga je verschillende analysemodellen schatten die telkens opbouwen in moeilijkheid.</p>
<p><em>1.1 Een eerste model test de hypothese dat kinderen met een hoger Iq en betere schoolprestaties (hier gemeten a.d.h.v. ‘Begrlezen’) in mindere mate gedemotiveerd zijn (lager scoren op ‘Demotivatiez’). Doe de analyse om deze hypothese te toetsen en schrijf je conclusies neer. Zorg ervoor dat de schattingen niet afhankelijk zijn van de meetschaal die werd gehanteerd voor de verschillende variabelen.</em></p>
<p><em>1.2 In een tweede model wil je specifiek de hypothese nagaan dat BSO-leerlingen sterker gedemotiveerd zijn dan de overige leerlingen. Je wenst deze groep dus af te zetten t.o.v. de rest van de leerlingen. Doe hiertoe het nodige analysewerk. Houd daarbij rekening met de resultaten uit 1.1: enkel variabelen die een significant effect hadden neem je op als controlevariabelen. Interpreteer de resultaten grondig.</em></p>
<p><em>1.3 Vervolgens wil je nagaan of het steek houdt wat collega’s zeggen. Je hoort hen namelijk vertellen dat vooral in het BSO-leerlingen met een hoog Iq gedemotiveerd geraken om verder te studeren. Ze zeggen dus dat het verschil tussen ‘slimme’ en ‘domme’ leerlingen aangaande demotivatie in het BSO groter is dan in de overige twee onderwijsvormen. Klopt dit volgens de gegevens die hier verzameld zijn? Wees volledig in de beschrijving van de analyses. Geef ook aan welk van de effecten het sterkste is volgens dit laatste model.</em></p>
<p><em>1.4 Ga na welk van de drie geschatte modellen het beste bij de data past. Analyseer en beargumenteer welk model het beste past.</em></p>
<p><em>1.5 Tenslotte bereken je de verwachte score in de steekproef en in de populatie voor een leerling die:</em></p>
<p><em>a) les volgt in het ASO, 1 SD hoger scoort op ‘Iqz’ en 0.5 SD lager op ‘Begrlezenz’</em></p>
<p><em>b) les volgt in het BSO, 2 SD hoger scoort op ‘Iqz’ en 1.5 SD hoger op ‘Begrlezenz’</em></p>
<p><em>Hanteer hiervoor de output van het beste model.</em> </p>
</section>
<section id="responsen" class="level1 unnumbered">
<h1 class="unnumbered">RESPONSEN</h1>
<p>Vooraleer we de analyses kunnen uitvoeren moeten we uiteraard de data inladen in <code>R</code> en tevens de OLP2 Functies activeren. Dit doen we bijvoorbeeld door gebruk te maken van de commando’s <code>load( )</code> en <code>source( )</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"DataZSO8.RData"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"OLP2 Functies.R"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="section" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="section">1.1</h2>
<ol type="a">
<li>Analyses</li>
</ol>
<p>We maken gebruik van z-scores om er voor te zorgen dat de schattingen niet afhankelijk zijn van de meetschaal die werd gehanteerd.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>DataZSO8<span class="sc">$</span>Iqz        <span class="ot">&lt;-</span> <span class="fu">scale</span>(DataZSO8<span class="sc">$</span>Iq)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>DataZSO8<span class="sc">$</span>Begrlezenz <span class="ot">&lt;-</span> <span class="fu">scale</span>(DataZSO8<span class="sc">$</span>Begrlezen)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>Model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Demotivatiez <span class="sc">~</span> Iqz <span class="sc">+</span> Begrlezenz, <span class="at">data =</span> DataZSO8)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Model1)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Demotivatiez ~ Iqz + Begrlezenz, data = DataZSO8)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.7764 -0.8135 -0.1589  0.6599  3.4039 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.01592    0.01768  -0.901  0.36786    
Iqz          0.06072    0.02253   2.695  0.00707 ** 
Begrlezenz  -0.14939    0.01902  -7.852 5.55e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9879 on 3141 degrees of freedom
  (560 observations deleted due to missingness)
Multiple R-squared:  0.01927,   Adjusted R-squared:  0.01865 
F-statistic: 30.86 on 2 and 3141 DF,  p-value: 5.345e-14</code></pre>
</div>
</div>
<ol start="2" type="a">
<li>Bespreking van de resultaten</li>
</ol>
<p>Dit model verklaart 1.9% van de variantie in ‘Demotivatiez’ en is bovendien statistisch significant (<em>F</em>(2,3141) = 30.86, <em>p</em> &lt; 0.001, Adj. <span class="math inline">\(R^2\)</span> = 0.019). Dus ook in de populatie zullen IQ en begrijpend lezen een klein deel van de variantie (Adj. <span class="math inline">\(R^2\)</span> = 0.019) in de mate van demotivatie verklaren.</p>
<p>Uit de parameterschattingen blijkt dat de hypothese dat kinderen met een hoger IQ en betere schoolprestaties lager scoren op ‘Demotivatiez’ niet volledig klopt. De hellingsgraad van ‘Iqz’ is 0.061 (<span class="math inline">\(\beta_1\)</span> = 0.061, <em>p</em> = 0.007). Dit wil zeggen dat voor elke standaardafwijking die een leerling hoger scoort op IQ, de leerlingen 0.061 standaardafwijkingen hoger gaan scoren op ‘Demotivatiez’. (Omdat zowel onze onafhankelijke variabelen als afhankelijke variabele zijn opgenomen als z-score, mogen we de effecten volledig in <em>SD</em> interpreteren.) De p-waarde is 0.007 en dus kleiner dan 0.05. Je kan m.a.w. verwachten dat IQ ook in de populatie een positief effect heeft op demotivatie.</p>
<p>De hellingsgraad van ‘Begrlezenz’ is echter negatief (<span class="math inline">\(\beta_2\)</span> = -0.149, <em>p</em> &lt; 0.001). Dit wil zeggen dat voor elke standaardafwijking dat een leerling hoger scoort op ‘Begrlezenz’, hij 0.15 standaardafwijkingen lager scoort op ‘Demotivatiez’ en dus minder gedemotiveerd is. De p-waarde is kleiner dan 0.05, dus ook hier verwachten we dat in de populatie begrijpend lezen een negatief effect gaat hebben op demotivatie. We kunnen dus besluiten dat kinderen met een hoger IQ meer gedemotiveerd zijn en kinderen met betere schoolprestaties minder gedemotiveerd zullen zijn in de populatie.</p>
<p>Het intercept (<span class="math inline">\(\beta_0\)</span> = -0.016, <em>p</em> = 0.368) is de score op ‘Demotivatiez’ voor een leerling die 0 scoort op ‘Iqz’ en ‘Begrlezenz’. Aangezien zowel ‘Iqz’ als ‘Begrlezenz’ z-scores zijn, betekent 0 scoren hier hetzelfde als gemiddeld scoren op Iq en Begrijpend lezen. De schatting voor het intercept is niet statistisch significant (<em>p</em> = 0.368). De kans dat de nulhypothese opgaat is dus te groot om deze te kunnen verwerpen. In de populatie is de verwachte score op ‘Demotivatiez’ dus 0. Aangezien ook ‘Demotivatiez’ een z-score is, betekent dit hetzelfde als dat er wordt verwacht dat er in de populatie gemiddeld gescoord zal worden op demotivatie.</p>
</section>
<section id="section-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="section-1">1.2</h2>
<ol type="a">
<li>Analyses</li>
</ol>
<p>Om hierop een antwoord te kunnen geven, maken we een dummyvariabele aan die aanstaat voor BSO en waarop leerlingen uit het ASO en TSO dus 0 scoren.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>DataZSO8<span class="sc">$</span>BSO <span class="ot">&lt;-</span> (DataZSO8<span class="sc">$</span>Ondvorm <span class="sc">==</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="dv">1</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(DataZSO8<span class="sc">$</span>BSO , DataZSO8<span class="sc">$</span>Ondvorm) <span class="co"># check of dummy goed is aangemaakt</span></span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
       1    2    3
  0 1730    0 1020
  1    0  920    0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>Model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Demotivatiez <span class="sc">~</span> Iqz <span class="sc">+</span> Begrlezenz <span class="sc">+</span> BSO, <span class="at">data =</span> DataZSO8)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Model2)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Demotivatiez ~ Iqz + Begrlezenz + BSO, data = DataZSO8)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.6451 -0.7771 -0.1278  0.6544  3.3951 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.09255    0.02110  -4.386 1.19e-05 ***
Iqz          0.08966    0.02289   3.916 9.18e-05 ***
Begrlezenz  -0.08399    0.02137  -3.930 8.66e-05 ***
BSO          0.34164    0.05112   6.683 2.77e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9823 on 3119 degrees of freedom
  (581 observations deleted due to missingness)
Multiple R-squared:  0.03328,   Adjusted R-squared:  0.03235 
F-statistic: 35.79 on 3 and 3119 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div style="page-break-after: always;"></div>
<ol start="2" type="a">
<li>Bespreking van de resultaten</li>
</ol>
<p>Uit de <em>Adjusted</em> <span class="math inline">\(R^2\)</span> kunnen we aflezen dat 3.2% van de variantie in de ‘Demotivatiez’ kan worden verklaard door het model. Gezien de p-waarde kleiner is dan 0.05 (<em>F</em>(3,3119) = 35.79, <em>p</em> &lt; 0.001, Adj. <span class="math inline">\(R^2\)</span> = 0.032) kunnen we zeggen dat IQ, score op begrijpend lezen en al dan niet les volgen in het BSO met een grote zekerheid ook een klein deel van de variantie in de afhankelijke variabele (‘Demotivatiez’) in de populatie zal verklaren.</p>
<p>Het intercept bedraagt -0.093. Dit wil zeggen dat een leerling in de steekproef uit het ASO of TSO die gemiddeld scoort op IQ en op begrijpend lezen een score van -0.093 SD op demotivatie zal behalen. Het intercept is statistisch significant afwijkend van 0 (<span class="math inline">\(\beta_0\)</span> = -0.093, <em>p</em> &lt; 0.001). We verwachten m.a.w. dat ook in de populatie leerlingen uit het ASO of TSO die gemiddeld scoren op IQ en begrijpend lezen, 0.093 standaardafwijkingen lager scoren dan gemiddeld op demotivatie.</p>
<p>Voor elke standaardafwijking dat een leerling hoger scoort op IQ, scoort deze leerlingen 0.09 standaardafwijkingen hoger op demotivatie, ongeacht de score op begrijpend lezen en onafhankelijk van de onderwijsvorm waarin de leerling les volgt. IQ heeft dus een positief effect op demotivatie en dit geldt ook voor de populatie (<span class="math inline">\(\beta_1\)</span> = 0.09, <em>p</em> &lt; 0.001). Voor elke standaardafwijking hoger scoren op begrijpend lezen daalt de score op ‘Demotivatiez’ met 0.084 standaardafwijkingen, onafhankelijk van de score op IQ en de onderwijsvorm. Hoger scoren op begrijpend lezen heeft dus een negatieve invloed op de mate waarin leerlingen gedemotiveerd zijn. Dit geldt bovendien niet alleen voor de steekproef, maar ook voor de populatie (<span class="math inline">\(\beta_2\)</span> = -0.084, <em>p</em> &lt; 0.001). Voor leerlingen uit het BSO verwachten we dat de score op demotivatie 0.34 <em>SD</em> hoger ligt dan bij leerlingen uit ASO of TSO. BSO leerlingen zijn dus inderdaad sterker gedemotiveerd dan de andere leerlingen, ongeacht hun IQ of score op begrijpend lezen. Ook dit effect is statistisch significant (<span class="math inline">\(\beta_3\)</span> = 0.342, <em>p</em> &lt; 0.001).</p>
</section>
<section id="section-2" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="section-2">1.3</h2>
<ol type="a">
<li>Analyses</li>
</ol>
<p>In deze vraag wordt verwezen naar een interactie-effect tussen ‘BSO’ en ‘Iqz’. Dit dienen we toe te voegen aan het model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>Model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Demotivatiez <span class="sc">~</span> Iqz <span class="sc">+</span> Begrlezenz <span class="sc">+</span> BSO <span class="sc">+</span> (BSO<span class="sc">*</span>Iqz),<span class="at">data =</span> DataZSO8)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Model3)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Demotivatiez ~ Iqz + Begrlezenz + BSO + (BSO * Iqz), 
    data = DataZSO8)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.7134 -0.7735 -0.1300  0.6594  3.3838 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.08608    0.02133  -4.035 5.60e-05 ***
Iqz          0.06049    0.02708   2.234   0.0255 *  
Begrlezenz  -0.08420    0.02136  -3.942 8.26e-05 ***
BSO          0.36847    0.05280   6.978 3.64e-12 ***
Iqz:BSO      0.09801    0.04862   2.016   0.0439 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9818 on 3118 degrees of freedom
  (581 observations deleted due to missingness)
Multiple R-squared:  0.03454,   Adjusted R-squared:  0.0333 
F-statistic: 27.89 on 4 and 3118 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ol start="2" type="a">
<li>Resultaten bespreken</li>
</ol>
<p>Volgens de Adjusted <span class="math inline">\(R^2\)</span> verklaart het model 3.33% van de variantie in ‘Demotivatiez’. Gezien het resultaat van de F-test (<em>F</em>(4,3118) = 27.89, <em>p</em> &lt; 0.001, Adj. <span class="math inline">\(R^2\)</span> = 0.033) kunnen we ook hier weer stellen dat dit model met grote waarschijnlijkheid ook in de populatie een deel van de verschillen in ‘Demotivatiez’ zal verklaren.</p>
<p>Het intercept bedraagt -0.086 (<span class="math inline">\(\beta_0\)</span> = -0.086, <em>p</em> &lt; 0.001). Een leerling die behoort tot ASO of TSO en gemiddeld scoort op begrijpend lezen en op IQ zal dus 0.086 <em>SD</em> lager scoren dan gemiddeld op demotivatie. Het intercept is statistisch significant. We verwachten dit ook terug te vinden in de populatie.</p>
<p>Op basis van de parameterschattingen kunnen we verder stellen dat als diezelfde leerling (gemiddelde score op Iq en op begrijpend lezen) les volgt in het BSO, deze 0.368 SD hoger scoort op ‘Demotivatiez’ (<span class="math inline">\(\beta_1\)</span> = 0.368, <em>p</em> &lt; 0.001). Een leerling uit BSO is dus meer gedemotiveerd dan leerlingen uit het ASO of TSO, ongeacht de score op IQ of begrijpend lezen.</p>
<p>Het effect van ‘Begrlezenz’ is negatief. Voor elke standaardafwijking die een leerling hoger scoort op ‘Begrlezenz’ scoort hij 0.084 standaardafwijkingen lager op ‘Demotivatiez’ (<span class="math inline">\(\beta_2\)</span> = -0.084, <em>p</em> &lt; 0.001), ongeacht zijn score op IQ en onafhankelijk van tot welke onderwijsvorm hij behoort.</p>
<p>Tenslotte blijkt uit de resultaten dat het effect van ‘Iqz’ inderdaad anders is voor leerlingen uit het BSO dan voor leerlingen uit het ASO of TSO. Een leerling uit ASO of TSO zal voor elke standaardafwijking die hij hoger scoort op IQ, 0.06 SD hoger scoren op demotivatie (<span class="math inline">\(\beta_3\)</span> = 0.06, <em>p</em> = 0.026), ongeacht zijn score op ‘Begrlezenz’. Een leerling uit BSO zal daarentegen voor elke standaardafwijking die hij hoger scoort op IQ, 0.158 <em>SD</em> hoger scoren op ‘Demotivatiez’ (0.158 = 0,06049 + 0,09801). Het effect van IQ op demotivatie is dus inderdaad groter voor BSO-leerlingen. Onderstaande figuur visualiseert dit interactie-effect. Gezien alle parameterschattingen statistisch significant zijn (<em>p</em> &lt; 0.05) zullen deze in de populatie met grote waarschijnlijkheid ook verschillend zijn van nul. Ook het interactie-effect is statistisch significant (<em>p</em> &lt; 0.05). Het effect van IQ op demotivatie is dus ook in de populatie groter in het BSO dan in de twee overige onderwijsvormen.</p>
<ol start="3" type="a">
<li>Uitdieping: figuur maken</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># EXTRAATJE VOOR DE LIEFHEBBERS!!</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># voor wie graag zelf interactie-effecten tussen een kwantitatieve </span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># en een kwalitatieve variabele plot</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co">#maak van de dummy een factor</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>DataZSO8<span class="sc">$</span>BSOfac <span class="ot">&lt;-</span> <span class="fu">factor</span>(DataZSO8<span class="sc">$</span>BSO, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"ASO of TSO"</span>,<span class="st">"BSO"</span>)) </span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co">#herschat het model met de variabele als factor</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>Model3bis <span class="ot">&lt;-</span> <span class="fu">lm</span>(Demotivatiez <span class="sc">~</span> Iqz <span class="sc">+</span> Begrlezenz <span class="sc">+</span> BSOfac <span class="sc">+</span> (BSOfac<span class="sc">*</span>Iqz),<span class="at">data =</span> DataZSO8) </span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Model3bis) </span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Demotivatiez ~ Iqz + Begrlezenz + BSOfac + (BSOfac * 
    Iqz), data = DataZSO8)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.7134 -0.7735 -0.1300  0.6594  3.3838 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   -0.08608    0.02133  -4.035 5.60e-05 ***
Iqz            0.06049    0.02708   2.234   0.0255 *  
Begrlezenz    -0.08420    0.02136  -3.942 8.26e-05 ***
BSOfacBSO      0.36847    0.05280   6.978 3.64e-12 ***
Iqz:BSOfacBSO  0.09801    0.04862   2.016   0.0439 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9818 on 3118 degrees of freedom
  (581 observations deleted due to missingness)
Multiple R-squared:  0.03454,   Adjusted R-squared:  0.0333 
F-statistic: 27.89 on 4 and 3118 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># eerst pakket ‘effects’ installeren! (staat niet in OLP)</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effects)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">effect</span>(<span class="st">"Iqz:BSOfac"</span>,Model3bis),</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">multiline=</span>T,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Visualisatie interactie-effect IQ en BSO"</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ZSO8_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="section-3" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="section-3">1.4</h2>
<ol type="a">
<li>Analyses</li>
</ol>
<p>Om modellen met elkaar te kunnen vergelijken dienen ze op dezelfde dataset geschat te zijn. Eigenlijk hadden we bij de start van de ZSO reeds kunnen opteren om een dataset aan te maken via <code>na.omit( )</code> waarin we enkel observaties weerhouden die geen ontbrekende waarden hebben voor al onze gehanteerde variabelen. We doen dit nu.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>DataZSO8b <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(DataZSO8[<span class="fu">c</span>(<span class="st">'Iqz'</span> , <span class="st">'Demotivatiez'</span> , <span class="st">'Begrlezenz'</span> , <span class="st">'BSO'</span>)])</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>Model1b <span class="ot">&lt;-</span> <span class="fu">lm</span>(Demotivatiez <span class="sc">~</span> Iqz <span class="sc">+</span> Begrlezenz, <span class="at">data =</span> DataZSO8b)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>Model2b <span class="ot">&lt;-</span> <span class="fu">lm</span>(Demotivatiez <span class="sc">~</span> Iqz <span class="sc">+</span> Begrlezenz <span class="sc">+</span> BSO, <span class="at">data=</span>DataZSO8b)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>Model3b <span class="ot">&lt;-</span> <span class="fu">lm</span>(Demotivatiez <span class="sc">~</span> Iqz <span class="sc">+</span> Begrlezenz <span class="sc">+</span> BSO <span class="sc">+</span> (BSO<span class="sc">*</span>Iqz), <span class="at">data=</span>DataZSO8b)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(Model1b , Model2b , Model3b)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Demotivatiez ~ Iqz + Begrlezenz
Model 2: Demotivatiez ~ Iqz + Begrlezenz + BSO
Model 3: Demotivatiez ~ Iqz + Begrlezenz + BSO + (BSO * Iqz)
  Res.Df    RSS Df Sum of Sq       F    Pr(&gt;F)    
1   3120 3052.4                                   
2   3119 3009.3  1    43.088 44.7016 2.708e-11 ***
3   3118 3005.4  1     3.917  4.0636    0.0439 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ol start="2" type="a">
<li>Resultaten bespreken</li>
</ol>
<p>Uit de output van de anova blijkt dat Model 3 de meeste variantie verklaart in de onafhankelijke variabele ‘Demotivatiez’. Dit blijkt uit de Residual Sum of Squares (<em>RSS</em>) die het laagst is voor het derde model. Dit onderstreept het belang van het opnemen van interactie-effect tussen Iq en BSO in het model.</p>
<p>Belangrijker, wanneer we kijken naar de p-waarde die de significantie van het verschil in <em>RSS</em> tussen Model2 en Model3 toetst (<em>F</em>(1) = 4.064, <em>p</em> = 0.044), dan zien we dat Model3 ook statistisch significant beter is. Dus ook in de populatie zal Model3 met het interactie-effect meer variantie verklaren in demotivatie dan Model2.</p>
</section>
<section id="section-4" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="section-4">1.5</h2>
<p>Uit de analyses in 1.4 blijkt dat Model3 het beste ‘Demotivatiez’ verklaart. We hanteren dus de schattingen uit dat model om de voorspelde scores te berekenen. We herhalen eerst de output voor dat model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Model3)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Demotivatiez ~ Iqz + Begrlezenz + BSO + (BSO * Iqz), 
    data = DataZSO8)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.7134 -0.7735 -0.1300  0.6594  3.3838 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.08608    0.02133  -4.035 5.60e-05 ***
Iqz          0.06049    0.02708   2.234   0.0255 *  
Begrlezenz  -0.08420    0.02136  -3.942 8.26e-05 ***
BSO          0.36847    0.05280   6.978 3.64e-12 ***
Iqz:BSO      0.09801    0.04862   2.016   0.0439 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9818 on 3118 degrees of freedom
  (581 observations deleted due to missingness)
Multiple R-squared:  0.03454,   Adjusted R-squared:  0.0333 
F-statistic: 27.89 on 4 and 3118 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ol type="a">
<li></li>
</ol>
<p>Voor een leerling die les volgt in het ASO, 1 SD hoger scoort op ‘Iqz’ en 0.5 <em>SD</em> lager op ‘Begrlezenz’ verwachten we dat deze in de steekproef en de populatie de volgende scores behaalt:</p>
<ul>
<li>in de steekproef: -0.086 + 0.06 + 0.042 = 0.016</li>
<li>in de populatie: -0.086 + 0.06 + 0.042 = 0.016</li>
</ul>
<p>Immers, de berekening gaat als volgt voor de populatie en de steekproef (voor beide gelijk, gegeven alle parameterschattingen statistisch significant zijn):</p>
<p><span class="math display">\[\hat{y}
= \begin{array}{c}
      \color{blue}{\beta_0} +
      \color{blue}{\beta_1}*\color{red}{\text{Iqz}} +
      \color{blue}{\beta_2}*\color{red}{\text{Begrlezenz}}+  
      \color{blue}{\beta_3}*\color{red}{\text{BSO}}  +
      \color{blue}{\beta_4}*\color{red}{\text{Iqz}}*\color{red}{\text{BSO}}\\
      \color{blue}{-0.086} +
      \color{blue}{0.060}*\color{red}{\text{1}} +
      \color{blue}{-0.084}*\color{red}{\text{-0.5}} +
      \color{blue}{0.368}*\color{red}{\text{0}} +
      \color{blue}{0.098}*\color{red}{\text{1}}*\color{red}{\text{0}}
\end{array}
= 0.016\]</span></p>
<ol start="2" type="a">
<li></li>
</ol>
<p>Voor een leerling die les volgt in het BSO, 2 <em>SD</em> hoger scoort op ‘Iqz’ en 1.5 SD hoger op ‘Begrlezenz’ verwachten we dat deze in de steekproef en de populatie de volgende scores behaalt:</p>
<p>in de steekproef: -0.086 + 0.12 + -0.126 + 0.368 + 0.196 = 0.472 in de populatie: -0.086 + 0.12 + -0.126 + 0.368 + 0.196 = 0.472</p>
<p>De berekening in meer detail:</p>
<p><span class="math display">\[\hat{y}
= \begin{array}{c}
      \color{blue}{\beta_0} +
      \color{blue}{\beta_1}*\color{red}{\text{Iqz}} +
      \color{blue}{\beta_2}*\color{red}{\text{Begrlezenz}} +  
      \color{blue}{\beta_3}*\color{red}{\text{BSO}}  +
      \color{blue}{\beta_4}*\color{red}{\text{Iqz}}*\color{red}{\text{BSO}}\\
      \color{blue}{-0.086} +
      \color{blue}{0.060}*\color{red}{\text{2}}  +
      \color{blue}{-0.084}*\color{red}{\text{1.5}}  +
      \color{blue}{0.368}*\color{red}{\text{1}} +
      \color{blue}{0.098}*\color{red}{\text{2}}*\color{red}{\text{1}}
\end{array}
= 0.472\]</span></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Gekopieerd!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Gekopieerd!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../ZSO/ZSO7.html" class="pagination-link" aria-label="ZSO7: Multivariate regressie en assumpties">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">ZSO7: Multivariate regressie en assumpties</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../Rapporteren.html" class="pagination-link" aria-label="Rapporteren">
        <span class="nav-page-text">Rapporteren</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© CC-By Universiteit Antwerpen, 2024</p>
</div>   
    <div class="nav-footer-center">

<div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Wij maken gebruik van cookies om de surfervaring te verbeteren en om de website te optimaliseren. IP-adressen worden niet bewaard.</a></div></div>
    <div class="nav-footer-right">
<p>Gemaakt met veel ❤ en <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>